### ISSUE TITLE
Quit-Button

### ISSUE THREAD

**Issue by Spielmops** [y20k/transistor#102]
I propose a quit-button, because transistor stays in the list of active apps and a message stays in the message-list.

Spielmops

**Comment by y20k** [comment]
Hi @Spielmops , 

thanks for you suggestion. But I think a quit button is not necessary.

Android apps generally do not need quit options. As soon as they are in the background (= not visible anymore) they do not use any CPU. They occupy some memory but as soon as the system needs memory it grabs it from applications that are in the background.

If not playing back music Transistor should not use any CPU at all. There is no harm to your battery. If Google Maps, Chrome etc. want more memory the system will give it to them and eventually kill Transistor automatically. Maybe staying in RAM even is an advantage because recreating the app from memory uses less CPU than starting it from zero,

Best regards

**Comment by Spielmops** [comment]
The developers of Firefox once thought  exactly as you. Now we have a quit-button. What the difficulty to insert one? And if it is for the good feeling of the users ...

Spielmops

**Comment by y20k** [comment]
> The developers of Firefox once thought exactly as you. Now we have a quit-button. 

I think it might be the other way around. I could not find the Quit option in Firefox on my phone. And googling the issue, I found an old blog entry explaining why Mozille did "retire the quit button" (see [Firefox, Android and Quit Buttons](https://blog.mozilla.org/ux/2013/04/quitting-on-android/)).

Anyway. Even if it was the way you remembered, Quit buttons would be still be not very common.  Reason:

> as soon as the system needs memory it grabs it from applications that are in the background.

I am going to stick with common design pattern to not offer a quit option. Sorry if you are disappointed. I will close this issue. Since I think your request is maybe interesting for other users I will keep it in [Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48).

**Comment by Spielmops** [comment]
Then please do something that no message stays in the notification area ..

Spielmops

**Comment by y20k** [comment]
Okay. I get that. The notification is bothering you. You should be able to swipe the notification when playback is off. But guess that is not what you want, right?

To leave a notification in the notification area after playback is not uncommon for music playing apps. This way you can start playback again easily. 

Earlier versions of Transistor did dismiss the notification as soon as a user pressed stop. But users did explicitly asked for it (#99).

**Comment by Spielmops** [comment]
I read about the request for the notification and understand that wish. That's the reason I asked for a quit-button.

Spielmops

**Comment by 9662** [comment]
Hi, sorry for the drive-by, but just to add to the quit-button debate, I do think android guidelines are often taken too literally.

The beauty of a Quit mechanism is not necessarily in terms of resource usage, but in that it takes the user back into a *known state*.

This is a cognitive rather than technical aspect.

**Comment by y20k** [comment]
That is an interesting point of view. I kind of agree, since I do like the way desktop operating systems hand over more responsibility to the user. On the other hand I am also not so sure if the convenience to not ever have to think about quitting apps outweighs freedom to manage that yourself.

Anyway. Unless not every app (or at least most of them) offer that feature, we have a **confusing situation**. 

Let me explain: Most of web apps do not offer a "Save" feature. So you do not have the option to control the **state** of your document. Autosave is from a technological standpoint probably an advancement comparable to Auto-Quit. 

Today I tried out the Lucidchart-Webapp - it does have a Save option. For me that did NOT give me peace-of-mind. **It introduced insecurity**. Does this app not save my progress? Or does it and is the save button snake oil?

Let's transfer that experience to Transistor (at least for me it would translate to): Most apps do not offer a Quit button, but Transistor does. So naturally one (or at least I) would think: Is something wrong with Transistor. I which way is it different than other apps? Does it drain my battery even when not active? Must I hit Quit every time I decide not to use it actively?

(Thinking about that: This is the way I think about "Bubble UPnP". In which way does it differ from other apps? Why do they have a Quit button?)

I recognize that the whole issue can be a hot topic 😺. Lets not discuss it too much, since I already did decide against that feature.

**Comment by Spielmops** [comment]
>Android apps generally do not need quit options. As soon as they are in the background (= not >visible anymore) they do not use any CPU

That's not the case, most apps do not use a quit-button and many apps need a quit-button, because they leave a process  active in memory. That's how Google wants it to collect data. That's "by design"

Music-apps that I know do not leave a notification if the music is stopped.

The notification-area is important and I don't want useless stuff there. The notification-place has to be empty so that I can easily recognize new messages. If transistor works in a way, that leaves a message, then it is important to be able to quit Transistor.

**Comment by y20k** [comment]
> because they leave a process active in memory

Apps are only **active** (= consuming battery) if they are visible, or if they start a background service. If Transistor is not playing music and if it is not visible, it does not use the **CPU** / consume **battery**. **Memory** is freed by the system automatically (see above). Keeping apps as long as possible in memory actually saves battery, because restarting apps that are in memory is more efficient.

> That's how Google wants it to collect data. That's "by design"

Interesting idea. But seriously what kind of data can you collect from a stopped application that you cannot collect while it is running?

> Music-apps that I know do not leave a notification if the music is stopped.

That is strange: **All** the music apps I use leave a notification when paused/stopped. (That would be: Bubble UPnP, Phonograph, Pocket Casts and Listen Audiobook Player)

> If transistor works in a way, that leaves a message, then it is important to be able to quit Transistor. 

You can swipe away the notification.

**Comment by Spielmops** [comment]
Crazy world: it is built this way "because of design" and not because it useful ...

Anyway: just deinstalled Transistor and installed: Simple Radio Player (com.voltov.simpleradioplayer). Notification vanishes with the stop-button. Quit-button and the app is not active any more.

Musicplayer with vanishing notification: VanillaMusic

Bye, Spielmops

**Comment by y20k** [comment]
Live long and prosper.

**Comment by 9662** [comment]
>> That's how Google wants it to collect data. That's "by design"
> Interesting idea. But seriously what kind of data can you collect from a stopped application that you cannot collect while it is running?

Application usage / popularity, by seeing what's been “cached”. Looking at the installed list does not tell you when or how often you use something. I do not know specifically whether Google do or do not do this, but that's one common technique.

**Comment by 9662** [comment]
> Today I tried out the Lucidchart-Webapp - it does have a Save option. For me that did NOT give me peace-of-mind. It introduced insecurity. Does this app not save my progress? Or does it and is the save button snake oil?

An action button provides positive confirmation that the desired action has happened. The same insecurity that you mention is what your users are experiencing by the *absence* of said action button (“OMG! Has the application not quit!?”)

In both cases, it is related to what a model user would expect. There is a strong expectation that, in the absence of an explicit mechanism, your application will be saving your important work, hence why you may not be worried by there not being a “Save” button and perhaps why that assumption may be challenged if you do see one (“Is it an additional mechanism, or the only one and my earlier expectation was wrong?”). In the case of an application being dismissed, however, there is no such strong expectation that all resources will be freed and things back to a known state—in fact, there is a mild expectation of that *not* happening, which is what is getting some of your users worried.

What you call “snake oil” is known as positive confirmation in UI circles, btw.

Incidentally, do you happen to have a link to where Google says “do not have a quit button”? I tried searching for that in their docs some time ago but the closest I could find were some suggestions that having one was not strictly necessary.
