### ISSUE TITLE
Playback stops and restarts periodically

### ISSUE THREAD

**Issue by stokholm** [y20k/transistor#106]
I'm on stock Android Nougat on a Nexus 6P, but had this problem with Marshmallow as well. I think it's related to doze, but I might be wrong.

The audio playback will stop after a period of about 10 minutes up to an hour, I think. After a period of several minutes (something like 5-30 minutes) playback will often resume. Sometimes this doesn't happen though (or maybe I didn't wait long enough). If it resumes it will keep playing for a period of a few seconds up to 15 minutes, maybe. After this point, I might as well stop Transistor, because playback has become so unstable.

Playback is extremely stable and never stops, when the phone is connected to power. Also the playback is stable and never stops, when I'm actually using the phone (screen on). So the problem only occurs when the phone is lying flat on its back and running on battery. These are the reasons why I think it's related to doze.

I've tried disabling Androids built-in battery optimization for Transistor, but this makes no difference. I read somewhere that you're using Androids audio playback for the stream, so maybe that's why disabling battery optimization for Transistor has no effect.

**Comment by y20k** [comment]
hi @stokholm 

sometimes Transistor just stops playback. I did experience that behavior, too. But I is rare and I never could find a reason for it.

Maybe your idea brings me on the right track. I never did check if it is related to the device being plugged in. Since debugging requires a USB connection it is hard to find the problem, if it occurs on battery only (debugging = plugged in). 

Anyway I will investigate it. Reading about the problems doze introduces, I think I do a lot of things right already: `startForeground`, return `START_STICKY`, `PARTIAL_WAKE_LOCK`.

The app does not acquire a WiFi lock yet. I will try to implement that next - and I will post my results here.

If you can reproduce the issue, it would be great, if you could test the solution for me and report your experience here.

**Comment by stokholm** [comment]
Sounds good, I'd be happy to help any way I can.

**Comment by y20k** [comment]
Great. Adding a Wifi lock is pretty straight forward. Since I had Android Studio still open, I just added the required code (see [commit](https://github.com/y20k/transistor/commit/310bcbfa17b8c1522fb326c51db1772e78509162)). (*)

Depending on your device setup you can test the changes right away by installing this signed APK: [transistor-app-test-2.1.6-wifilock.apk](https://www.dropbox.com/s/hd4v3hw673lnej8/transistor-app-test-2.1.6-wifilock.apk?dl=0). Alternatively just wait for the next release (~ mid-October).

(*) This is a bit unusual 😸. I am normally not that fast at answering since Transistor is a project I do in my spare time.

**Comment by stokholm** [comment]
Sorry I can't bring good news. I had it running for about an hour, but it didn't help. Still the same behavior.

**Comment by stokholm** [comment]
Any time. Really. I see the problem (or similar) was discussed on Stack Overflow: http://stackoverflow.com/questions/35438786/doze-mode-app-standby-during-audio-playback

There are some good suggestions and links in that thread. Might not be new to you, but in case it's useful, I thought I'd share.

**Comment by y20k** [comment]
Hi @stokholm 

> I've tried disabling Androids built-in battery optimization for Transistor ...

You are referring to this System setting right? [How to turn off doze mode for specific apps in Android Marshmallow](http://www.greenbot.com/article/2993199/android/how-to-turn-off-doze-mode-for-specific-apps-in-android-marshmallow.html). I am trying this right now, too. Transistor is running without "battery optimization" and I am keeping my fingers crossed.

> ... but this makes no difference. 

(I wanted to see myself if playback still fails after one hour.) If shutting of doze mode does not help, than the problem is probably not related to Doze, after all? This whole disconnecting issue is really strange.

> problem (or similar) was discussed on Stack Overflow

Thanks! I think I have seen post you linked before, but I am not sure. From the Stack Overflow discussion I came to another interesting post on the topic: [Issue 193802](https://code.google.com/p/android/issues/detail?id=193802). The a project member comments: "Android N contains the fix" ([comment 9](https://code.google.com/p/android/issues/detail?id=193802#c9)).

> I'm on stock Android Nougat on a Nexus 6P

You should not experience the problem :frowning: 

Anyway. Assuming the problem is still related to Doze the above discussion has one fix for Android Marshmallow "The work around is to to have the foreground service run in a different process." ([comment 17](https://code.google.com/p/android/issues/detail?id=193802#c14)). While this may sound easy: This would introduce a whole lot of problems. Syncing the playback state of the background service to the UI would be become very cumbersome. Plus: The core media player is already running "asyc" (= on a different threat). So I am not sure if putting the whole Service in another process would help.

There is **one thing though** that connects the core media player to the main app thread. That would be the MetadataHelper that strips out the current song metadata. I compiled a test version of Transistor that comes without metadata extraction. 

[transistor-app-test-2.1.6-no-metadata.apk](https://www.dropbox.com/s/2dr7vp7ow6mqxuk/transistor-app-test-2.1.6-no-metadata.apk?dl=0)

If you find the time. It would be great, if you could test, if it still fails in your usage scenario.

**Comment by stokholm** [comment]
I can't say for sure that this is working, but I've had the radio running for the past 80-90 minutes, without any interruptions. I am on a different Wi-Fi network though, so testing conditions are not exactly the same.

I will test at home as soon as I get a chance. Maybe tonight or definitely tomorrow.

But anyway, thanks so much for trying to fix this.

**Comment by stokholm** [comment]
Sad news. This morning, at home, it played for 30 minutes before stopping, and resuming 3-5 minutes later. :-(

**Comment by y20k** [comment]
I on the other hand had a phenomenal 4 hour playback of without any gaps yesterday. phone was unplugged and playback did only end, when the phone had to shut down.

As I wrote before. I do experience connection break-ups, too. But they are really hard to predict on my test devices.

The little I have learned so far about the probable cause:

1. it is not the metadata extraction (since you did experienced break-ups even with deactivated metadata display.
2. it is probably not Doze since you are running Nougat - and the Doze problem of disregarding wakelocks should be fixed in Android 7
3. Transistor can handle network outage. I does reconnect, when I put the phone in and out of airplane mode.

What is left? 
a. Maybe some kind of strange behavior on the server side? 
b. Maybe a local network issue that is not reproduce-able by airplane mode?

**Comment by Illusion65** [comment]
HI, I just began using your app and I really appreciate it's simplicity. I moved from TuneIn to Radio.net to SimpleRadio, but tired of all of them as they became bloated, or overloaded with ads and pushes to upgrade.  I'd much rather be part of an open source initiative!

It's been a few years since I programmed Android apps, so I've not kept up with the environment or features, but I'm going to dive back in, hoping I can contribute here.

I'm experiencing what could be the same problem as this bug report, but on a different time-scale. As long as the phone is active (not in Doze), Transistor seems to work fine, but within a minute or two of going into Doze, I experience the stop/start stuttering. Estimate: 20-30 sec playing, then 15-20 sec quiet. Sometimes growing longer if I wait a few min.

My thought was that this would be much easier to debug than the original bug's time-scale.  So, how can I help? Are there code areas that you are suspicious of where we could add debugging tests/assertions?  Perhaps a loop for which you'd like to see timing info?

In the meantime, I'll download the latest code and Android dev environment.  Currently running Transistor v2.1.7 from Fdroid's repository.

My phone: Samsung Note4 (SM-N910W8), running 6.0.1, kernel 3.10.40-8000148

Cheers,
Doug

**Comment by y20k** [comment]
Hi Doug,

I would really appreciate a helping hand with this! I will try to point you to the "critical" sections in the code - to give you a head start.

**I: Handing a stream to the Android MediaPlayer**

[PlayerService.java#754](https://github.com/y20k/transistor/blob/8ac676013ab387df9903a0931d9e6a4415f1007e/app/src/main/java/org/y20k/transistor/PlayerService.java#L754): A stream without metadata extraction - for HLS streams, because the MetaDataHelper does not work with HLS.

[PlayerService.java#756](https://github.com/y20k/transistor/blob/8ac676013ab387df9903a0931d9e6a4415f1007e/app/src/main/java/org/y20k/transistor/PlayerService.java#L758): A local proxy created by Transistor's MetaDataHelper (extracts Shoutcast-style Metadata).

**II: Reconnecting the stream**

[PlayerService.java#353](https://github.com/y20k/transistor/blob/8ac676013ab387df9903a0931d9e6a4415f1007e/app/src/main/java/org/y20k/transistor/PlayerService.java#L353): Transistor tries to reconnect up to ten times, if MediaPlayer reported back an error.

[PlayerService.java#257](https://github.com/y20k/transistor/blob/8ac676013ab387df9903a0931d9e6a4415f1007e/app/src/main/java/org/y20k/transistor/PlayerService.java#L257): Sometimes the stream gets restarted server-side. MediaPlayer receives a stream completed message. Transitor restarts the stream in this case.

I did try serveral things. Most of them are documented above in this discussion. I added a wifi lock. I tried to turn off Doze mode manually. I deactivated metadata functionality, to rule out that there is something wrong with the MetaDataHelper proxy.

Okay. So much for now. Feel free to contact me anytime, if you want to know why I implemnted the app the way I did. Or if you need any other assistance.

Christian

**Comment by Illusion65** [comment]
Hi Christian,

Thanks for getting back to me! I've been out with pneumonia for a little 
while (& also taking care of my 2yo son), sorry for the delay.  I have 
used the time productively to read up on media player issues & bugs. I 
think I found an issue that seems to be affecting a lot apps that need 
to run continuously (and avoid Doze), but it's difficult to tell whether 
it should affect a foreground MediaPlayer service.  Google acknowledged 
it is a bug in the Marshmallow OS, fixed in Nougat (so only Android 6 
phones).

I haven't had a chance to look over your code very thoroughly, but what 
I have examined looks great; thanks! As near as I can tell, it seems 
that the extra that's required in your code to bypass this bug is to 
make the service run in separate process.

Here are some links discussing the bug:

This is a long Google+ discussion 
<https://plus.google.com/+AndroidDevelopers/posts/94jCkmG4jff> that 
uncovers the bug and the work-around. I think most of the productive 
discussion was about a year ago (up to ~33 weeks ago) - with Dianne 
Hackborn at Google acknowledging the bug and Petr Nalevka pushing until 
the problem is obvious.  Also, later in this thread, is a series from 
someone who's doing development on a Huawei phone and they're noticing 
the much shorter time issues that I'm noticing on my Samsung. Possibly 
Huawei's non-stock Android has been modified for shorter Doze timeouts. 
I wonder if that's what I'm grappling with, since Doze isn't supposed to 
happen if the phone is plugged in, but I do notice dropouts whether or 
not it's plugged in, and usually starting within the first 5-15 min.

Ian Lake (also from Google) covers the issue in brief in this comment on 
StackExchange 
<http://stackoverflow.com/questions/37869201/how-does-doze-mode-affect-background-foreground-services-with-without-partial-f/37869501#37869501>.  
This is Petr's bug report 
<https://code.google.com/p/android/issues/detail?id=193802>. He's doing 
sensor data acquisition for a sleep app, so it's not the same as 
background music, but it's the only lead I found that sort of makes sense.

Anyway, I'll get around to trying out the separate process for the media 
player soon, but I wanted to let you know where I'm heading with my bug 
hunting.  Also, I'm set up, but haven't yet had the time to connect my 
phone to debug with my laptop, so if I see something from that, I'll let 
you know.

Cheers,

Doug

**Comment by y20k** [comment]
Hi @Illusion65 ,

great to hear from you. You dug some interesting stuff. I think I did stumbled over Petr's bug report, too. Because I remember that the specific issue should be fixed in Nougat. 

@stokholm (who opened this issue here) does experience the problem although he is om N. What does that mean for a possible solution? I don't know. Maybe handing the playback over to a separate process will help. Right now playback is just an AsyncTask. The only problem I can see is that inner-app communication is probably going to become a bit trickier. 

Anyway. Take your time. Have fun with your son!

**Comment by y20k** [comment]
Hi @Illusion65 & @stokholm,

I am experimenting with Transistor's audio back-end. I will maybe switch from MediaPlayer to [ExoPlayer](https://developer.android.com/guide/topics/media/exoplayer.html). 

It is possible that as a side effect the Doze-related problem will vanish. I need beta testers. If you interested in helping, please head over to issue #120 and report your findings.

Thanks & take care.

**Comment by Illusion65** [comment]
Hi! I was just about to msg you about this. I've been looking thru the issues related to MediaPlayer and think it's just too difficult to make work consistently for audio & was looking at integrating the ExoPlayer. It seems much more robust!

I think the problems I have with most players (I think all that use MediaPlayer) will vanish, but Doze-related issues seem very widespread and system-level buggy, so will still need the special work-around.

So, yes, I'm interested in beta-testing! I'll check out the issue. Thanks,
Doug

**Comment by stokholm** [comment]
I will test over the coming days and report my findings. Thanks!

**Comment by y20k** [comment]
[v.2.2.1](https://github.com/y20k/transistor/releases/tag/v2.2.1) is out. It comes with the new playback library  `ExoPlayer`. I hope the issue is fixed. I will close this it for now. Feel free to reopen, if you still got problems.
