### ISSUE TITLE
M3U8 Read error

### ISSUE THREAD

**Issue by azizsan** [y20k/transistor#108]
Read error

Hello, very nice application.
but http://trtcanlifm-lh.akamaihd.net/i/RADYO1_1@182345/master.m3u8 gives extension file read errors. can you help me.

**Comment by y20k** [comment]
Hi there,

I had a similar issue a couple of month ago (see #36). Some files of the type m3u8 do not simply contain a mp3 streaming link but contain a link to another m3u8 file. Like a Russian doll.

Transistor does not support that kind of playlist file. Not because I am too lazy extract the data from the second file, but because the second file does not contain any link that the official [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) library will play.

Sorry. I guess there is no easy solution here. I know that other players can handle those kinds of files somehow. But I am just a part time developer - and if the above mentioned library does not play back a stream I am stuck. I do not want to change the base engine or add a second playback library.

Best regards.

**Comment by azizsan** [comment]
I understand.
most followed radio channel in Turkey I was very sorry :(


Adding applications AdMob plugin Can I run in Turkey.

meanwhile a nice thought and application  Thank you

**Comment by y20k** [comment]
Hi there,

I did poke around a bit more. It turned out that the second m3u8 file within the first m8ua file can be played back by MediaPlayer even though it is a plain text file. m3u8-files often are used to do [HTTP Live Streaming (HLS)](https://en.wikipedia.org/wiki/HTTP_Live_Streaming). Android supports this kind of media (see [Supported Media Formats](https://developer.android.com/guide/appendix/media-formats.html)).

Why does Transistor not play these files? The MetaDataHelper (@pelya) supports Shoutcast media but not HLS.

I wrote a quick check if the provided file is HLS. If so Transistor will not use the MetaDataHelper. That means: no song titles for HLS files - but hey at least it should play back m3u8 (see [commit](https://github.com/y20k/transistor/commit/cc6050b3f02fb8d118910b9347112ae6e2e464d3)).

If you are interested to beta-test this feature, here is an APK for you: [transistor-app-test-2.1.6-hls.apk](https://www.dropbox.com/s/9ggoxq7a2sexzge/transistor-app-test-2.1.6-hls.apk?dl=0)

**Comment by y20k** [comment]
New updated Test-APK for HLS type streaming. This should now play the BBC-HLS streams mentioned in #36. --> [transistor-app-test-2.1.6-2-hls.apk](https://www.dropbox.com/s/g80s99yrllmxgfx/transistor-app-test-2.1.6-2-hls.apk?dl=0) (see [commit](https://github.com/y20k/transistor/commit/8c2e7344ef6212490deb008c6899b155741992c4))

**Comment by azizsan** [comment]
Thank you for the update.

**Comment by y20k** [comment]
Hi there

the next version ([v2.1.6](https://github.com/y20k/transistor/releases/tag/v2.1.6)) features limited HLS support. No station metadata though. I tried to use some of the metadata extracting methods that Android offers but with negative results.

Transistor also cannot play streams with adaptive bit rates. Those stations change streams depending on the available bandwidth. In practice playback will stop as soon as a station changes streams. There might be a way to fix this - but as far as I can see this technology is mainly used for HLS video streaming.

So. Good luck with Radyo 1 and have fun. FYI: Next version also features a Turkish translation :-) :tr: 

I will close this issue for now.
