### ISSUE TITLE
Android Auto support

### ISSUE THREAD

**Issue by c00ller** [y20k/transistor#112]
Now that Android Auto is available for any phone, it would be great if Transistor was compatible with the music function in the app. In case you are not familiar, Android Auto has a music tab that can be used by any supported music app. [Here are the apps that are currently supported](https://play.google.com/store/apps/collection/promotion_3001303_android_auto_all?hl=en). I would love to be able to easily control station switching in Transistor through the driver friendly interface in Android Auto.

**Comment by y20k** [comment]
Hi there,

supporting Android Auto and supporting [Next/Previous media buttons](https://github.com/y20k/transistor/issues/89) require both an implemention of MediaBrowserService. I did try to do that (#89) - but I somehow could not figure out how to do that properly. 

I will leave this issue open, because I want to give it a second try. Any progress I make I will comment here. But do not get your hopes up yet. I am a bit time constraint - and I wasn't able to figure it out the last time.

Best regards

**Comment by y20k** [comment]
I need to preface this: This feature is still far away from being finished. I just wanted to let you know that from time to time I am working on it.

So last week I spent several hours on Android Auto and I got some of the interface elements working (see screenshots). That is progress compared to the last time I tried it. 

![2017-08-28-13 30 34](https://user-images.githubusercontent.com/9103935/29771922-6f9e978a-8bf6-11e7-9ab4-cafdfa3cdb36.png) ![2017-08-28-13 29 46](https://user-images.githubusercontent.com/9103935/29771921-6f993eca-8bf6-11e7-9f0e-a3781e4051bd.png)

I think I now understand how to implement the feature. That is progress, too :-) The problem now is that I need to switch the way Transistor stores and handles it's radio station data to a whole new data structure:

Transistor's `PlayerFragment` and `ListFragment` each need an additional data abstraction in form of `MediaBrowserCompat`. (I am writing this here to remind my future self where to pick up the work.)

Some interesting guides I found (also a reference for future-me)

https://developer.android.com/guide/topics/media-apps/audio-app/building-a-mediabrowserservice.html

https://developer.android.com/guide/topics/media-apps/audio-app/building-a-mediabrowser-client.html

https://developer.android.com/training/auto/audio/index.html

https://medium.com/google-developers/mediabrowserservicecompat-and-the-modern-media-playback-app-7959a5196d90

https://medium.com/google-exoplayer/the-mediasession-extension-for-exoplayer-82b9619deb2d

**Comment by y20k** [comment]
Turns out that I already was very close when I wrote the last post two days ago. Today I got playback and browsing running in the [Android Auto App](https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead&utm_source=adc) on my phone.

I opened a new issue (#148) because I need testers for the feature who have a car. 

I will will close this issue. Discussion about this feature can continue under the new issue.
