### ISSUE TITLE
stream resumes a few seconds and starts buffering after connection loss

### ISSUE THREAD

**Issue by twouters** [y20k/transistor#113]
It's a bit hard to describe the issue, but I'll give it a shot.
During my commute I pass two, or three, spots where I have nearly no reception for a few seconds.

Transistor pauses playback for a few seconds when the reception/connection is lost, resumes when the connection returns and stops playing after another few seconds.
Then it starts buffering again and starts playback as normal.

I have the feeling that MediaPlayer pauses and resumes the remaining buffered data when it detects a network failure and then starts to buffer again when the (too small) buffer has been depleted. (Wild guess :-))

I have not looked at this in detail, but ExoPlayer could provide access to more fine grained tuning of networking/buffering stuff - https://google.github.io/ExoPlayer/

Have you ever considered implementing the ExoPlayer API as a replacement for MediaPlayer?

**Comment by y20k** [comment]
> Have you ever considered implementing the ExoPlayer API as a replacement for MediaPlayer?

Yes. I did consider it. Mainly to support more audio formats. 

A switch to another library for playback is not trivial. New bugs may/will be side effect. Plus: The maintainer of the library could loose interest in it etc. Since the time I can (and want to) spend on Transistor is limited, it is necessary to chose wisely. 

So when I started out building Transistor I chose MediaPlayer, since it is part of core Android. A safe bet. ExoPlayer is a Google Project, too. Okay Google likes to kill its projects. But still, ExoPlayer would be compared to other libraries a save bet, too.

So ExoPlayer seems to be a good alternative. I am not sure If it helps with your problem. But there are probably other benfits, too (more audio formats).

**Comment by y20k** [comment]
Hi @twouters ,

there is a beta version of Transistor that uses [ExoPlayer](https://developer.android.com/guide/topics/media/exoplayer.html). Are you interested in testing it?

If so, please head over to issue #120 and report your findings.

Thanks & take care.

**Comment by twouters** [comment]
I would love to test this, but I'm having BT issues with LineageOS and my car.
I'll test it out once I've been able to fix those :-)

**Comment by twouters** [comment]
Improved in beta ExoPlayer build.
