### ISSUE TITLE
Auto-add radio icons

### ISSUE THREAD

**Issue by sammanesh1** [y20k/transistor#114]
Auto-add radio icons by having like a database filled with icons which searches for icons within it depending on the radio streaming link entered within the app

for example, for BBC Radio 1 (http://www.listenlive.eu/bbcradio1.m3u), when that link is entered in-app, the app searches through a cloud-based database for the icon associated with that station.

**Comment by y20k** [comment]
Hi there, 

a while ago I was contacted by the creator of http://www.radio-browser.info/ (see #94)- he built a free and open directory of radio streams, that I really like. The directory contains stream URLs as well as station icons.

Implementing a radio-browser.info search feature would totally solve the problem that adding stations is a bit cumbersome at the moment. And it would be a solution to your suggestion. 

It would also create a dependency to a web service that I do not have any control of. Sure I could roll my own version of radio-browser on my own server since the underlying software is open source 👍. But still: Transistor would cease to be the small standalone app I intended it to be.

Anyway. I would need to way the comfort for users that tying my app to a web-service would bring to the possible problems that that could cause (server "down" times, no control over the source). Also in the mix: I would need to have to code the whole thing myself 😸. 

So for now I did decide against implementing this feature (see #94)). It is still on my radar though, meaning: It still could come, but not with one of the next updates. sorry.
