### ISSUE TITLE
Google Cast support

### ISSUE THREAD

**Issue by Sofoca** [y20k/transistor#115]

**Comment by y20k** [comment]
Hi there,

Thanks for suggesting Google Cast support! Cast requires to have Google Play Services installed on the user side and it requires me to register at Google as a cast developer. Cast is not an open standard, as far as I see it. 

Since I do not want to support non-free standards I did decide against implementing Google Cast (see #47). At least for now. If in the future Cast becomes a quasi-standard, I might change my mind. No need to fight against windmills at such a point.

Since I personally use a Raspberry Pi and [Volumio DLNA](https://volumio.org/) there is an incentive for me to implement DLNA. Maybe next year :-)

Best regards and a happy Christmas / holiday season.
