### ISSUE TITLE
Feature request: set as alarm

### ISSUE THREAD

**Issue by JonnyTech** [y20k/transistor#118]
Can you possibly add the ability to start at a specific time so that it can be used as an alarm or when a particular show starts?

**Comment by y20k** [comment]
Hi there,

I have considered adding the capability to set alarms within Transistor before. While I too think that this could be a neat new feature ... there are also reasons not to implement this.

The most important one would be: Complexity. The main goal of Transistor is simplicity (no settings). It just displays a list of m3u files and offers to play them back. 

Adding alarms would introduce several new administrative screens. Setting recurring alarms, one time alarms. What happens when a user deletes a station while an alarm is still active.

The intended way / or better: on possible way to accomplish the alarm feature is to use [Tasker](https://tasker.dinglisch.net/) or a similar app that can start Transistor with certain parameters.

Right now Transistor supports **Autostart for the last played station**.

Here are the parameters for Tasker:
- Activity: org.y20k.transistor/org.y20k.transistor.MainActivity
- Action: org.y20k.transistor.action.SHOW_PLAYER
- Extra: LAST_STATION | true
- Extra: PLAYBACK_STATE | true

**Comment by JonnyTech** [comment]
Thanks for the feedback. I had considered uding Tasker but for various reasons decided against it.

**Comment by y20k** [comment]
Since I do not plan to implement an alarm clock feature, I will close this issue and reference it at [Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48).

Sorry to disappoint you.
