### ISSUE TITLE
Support the .pls playlist format (audio/x-scpls)

### ISSUE THREAD

**Issue by guillaume-uH57J9** [y20k/transistor#124]
Hi,

This is a feature request to improve the (already great) transistor android app

Please consider adding support for the .pls playlist format https://en.wikipedia.org/wiki/PLS_%28file_format%29

Example of pls files for various webradios: 
* SomaFM https://somafm.com/ https://somafm.com/groovesalad256.pls https://somafm.com/sonicuniverse192.pls
* Radio Valencia  http://radiovalencia.fm/radiovalencia3.pls

**Comment by guillaume-uH57J9** [comment]
transistor's source code has reference to the PLS format, but when placing both M3U and PLS files in transistor's directory, I only see the M3U ones in the application, PLS files appear to be ignored

**Comment by y20k** [comment]
Hi @guillaume-uH57J9, 

I was able to add both SomaFM streams without any problems. By adding I mean: Tapping on the links you posted and/or pasting in those links into the Add dialog. Adding the raw PLS files straight into the Collection folder on your device through a file manager will not work. 

I was not able to add Radio Valencia. The problem is, that the _radiovalencia3.pls_ has a wrong encoding server-side. Its MIME type is  `application/pls+xml`. While that sounds like a PLS playlist MIME type, it actually is a MIME type for [Pronunciation Lexicon Specification (PLS)](https://www.w3.org/TR/pronunciation-lexicon/).

The hard fix for your problem would be: Contact Radio Valencia and tell them to fix their MIME type 😄. The medium hard fix would be: I could loosen the MIME type restrictions within the code (But I am a bit reluctant to do so.).

The easy fix: Just add http://live.str3am.com:3010/live through the Add dialog. This URL can be found within the _radiovalencia3.pls_ file when you open it with a text editor.

**Comment by guillaume-uH57J9** [comment]
Hi @y20k thanks for the feedback. 

You're correct about Radio Valencia, they have a MIME type issue; I am contacting them to report this. 

Regarding webradios with valid MIME types (SomaFM et al.): 

Adding SomaFM's URLs using Transistor's UI does work, it seems by converting the PLS playlist to M3U and saving it into the Collection folder. 

In my use case I am adding both M3U and PLS playlist files into the Collection folder. The folder actually is synchronized (by [syncthing](https://github.com/syncthing/syncthing-android)) for use in other devices and audio players. I find it's a good way to manager a radio list (add new cool radios, fix outdated stream URLs, ...). 

There's a way around by converting to M3U so I can listen to SomaFM :) 
But support for reading PLS from the Collection folder would still be nice.

**Comment by guillaume-uH57J9** [comment]
Update for Radio Valencia: someone from the station answered me, they fixed the MIME Type

**Comment by y20k** [comment]
> But support for reading PLS from the Collection folder would still be nice.

Okay. I will leave this issue open for now. I need to consider the implications. Originally I wanted to have control over what is stored in the Collections folder.

**Comment by y20k** [comment]
> support for reading PLS from the Collection folder would still be nice

Transistor already has a method to read PLS files. This method is used when downloading a file from the network or when opening it on device. Transistor then automatically imports the station and puts it as an M3U in the Collection folder. 

I theory I could re-use that method to implement your feature request. But reading would not be enough for your scenario. In case the user wants to rename a station Transistor would need a write feature, too. That in turn would bring more minor complications. 

So I think: For most users the existing way Transistor works is fine. I do not want to change that. The Collection Folder will continue to only host M3U files.

(PS. This is a hobby project. I do not have a lot of time to invest here. Sorry)
