### ISSUE TITLE
Station SWR3 and SWR1 not playing

### ISSUE THREAD

**Issue by Doggy77** [y20k/transistor#138]
The german radio stations "swr1" and "swr3" are not playing. The provide aus "m3u" for web Radio, IT seems as if transistor hast a problem with this. 

Example:
http://mp3-live.swr.de/swr3_m.m3u

Adresses are gathered from the official page:
http://www.swr.de/empfang/webradio-hoeren-alle-streams/-/id=3786/did=13840718/nid=3786/1pclwly/index.html

Greets, 
Doggy77

**Comment by y20k** [comment]
Hi @Doggy77 ,

I stumbled upon this issue earlier this week, too. The problem is that the M3Us on this site contain two stream URLs. Only one of them works. Transistor has does not have a validation feature. It just grabs an URL from a given file/location.

In this case it grabbed the wrong URL. It seems that all stations of the ARD group ditched akamaistream.net as stream CDN in favor of addradio.de on June 1st.. I had similar problems with Radio Bremen and NDR streams. They all started to play back again when I changed the URLs to the addradio.de versions.

The quick fix on my side would be: Let Transistor not choose the last URLs in an M3U, but the first - assuming the order of URLs is intentional ("The good streams first"). I will implement that in the next version of Transistor. Long term fixes would be a stream validation feature and the ability to store more one raw stream URL per station. But I am not sure if it is worth it (Transistor is a hobby project). Maybe a project to contribute for some else.

The very short fix for your would be. Add the addradio.de versions of SWR1 & SWR3 (can be found inside of the M3Us)

SWR 3
http://swr-swr3-live.cast.addradio.de/swr/swr3/live/mp3/128/stream.mp3

SWR 1 BW
http://swr-swr1-bw.cast.addradio.de/swr/swr1/bw/mp3/128/stream.mp3

SWR 1 RP
http://swr-swr1-rp.cast.addradio.de/swr/swr1/rp/mp3/128/stream.mp3

Best regards
y20k

**Comment by y20k** [comment]
FYI. I wrote a message to the responsible department at SWR. They confirmed that SWR was switching stream providers. By the way: Deutschlandfunk switched away from akamaistream.net too.

Here is the relevant quote from the SWR answer:
> Zum 01.06. wechselte der SWR seinen Streaming-Provider für Audio-Livestreaming. Wir hatten während der Migrationsphase beide Streams gelistet und werden die Akamai-Streams nun zeitnah aus den Containern entfernen.
