### ISSUE TITLE
GUI shows multiple active livestreams

### ISSUE THREAD

**Issue by PeKaBo** [y20k/transistor#139]
- start a fresh instance of Transistor
- select the first item (livestream) to play and press the play button on the next screen
- go back to the main screen
- select the second item (livestream) to show the next screen: you will see a play button
- go back to the main screen
- select again the second item (livestream) again to show the next screen: you will see a **stop** button!
- press the Android-Home-Button to show the Android-Home-Screen
- open the Android-Notification-Center und touch the Transistor-Notification to open the Application
- press the Back-Button to see the Transistor-Main-Screen
- you will see two active Live-Streams

This behavior is 100% reproducible

**Comment by y20k** [comment]
I did look into it. The problem is my sloppy code that decides the UI state of the Now Playing screen (stopped, loading, playing). The code is closer to guessing the state than knowing it. There is maybe an easy short-term fix for that. But I think the app need better awareness of its state. 

My plan for now is to try to make the [CollectionAdapter](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/CollectionAdapter.java) a [lifecycle aware component](https://codelabs.developers.google.com/codelabs/android-lifecycles/#0). ... with the goal that both the list of stations and the now playing screen share the same state information. That is not too complicated, but takes some time. I will tackle that issue after my vacation 🌞.

**Comment by y20k** [comment]
Okay. I finished the above mentioned transition of Transistors backend to ViewModel/LiveData. Yay. As far as I can see this bug is fixed. At least on my phone :-) Feel free to reopen this Issue, if there are still problems.
