### ISSUE TITLE
Option to remove the station image (was: Add option to disable lockscreen cover)

### ISSUE THREAD

**Issue by Wiredframe** [y20k/transistor#145]
Being able to disable the lockscreen cover would be nice since the images aren't that great anyway.

**Comment by Wiredframe** [comment]
Also adding an option to remove the image and replace it with a standard play or note icon would be nice.

**Comment by y20k** [comment]
Hi there, 

Thanks for posting your feature requests here!! I have thought about it. I think I am not going to introduce a setting for disabling the lockscreen cover. There are two "reasons" for that.

**First:** I do not want to introduce any settings in Transistor ;-)

**Second:** Given my opinion on settings for Transistor, I could consider killing the lockscreen feature completely. **I agree** that if you do not manually change a station image, **it looks ugly** blown up on the lockscreen. But there are people who curate their radiostation list with images. They probably like the feature. And: The cover is shown because it is embedded in the so called MediaMetadata. The MediaMetadata is read/interpreted in a variety of places automatically. So the hypothetical lockscreen setting / or the removal of that feature would not only make the icon disappear on the lockscreen, it also would also affect Android Wear Users for example. Okay and lastly: Removing features (which you did not suggest, I know :-) ) .... removing feature angers existing users.

**Comment by y20k** [comment]
> adding an option to remove the image ...

That is an option that I could implement. I will leave this issue open. Lets see. I need to think about it.

In the meantime: I you really dislike the Station icon, you can delete its PNG file in the folder `Android/data/org.y20k.transistor/files/Collection`

**Comment by y20k** [comment]
> adding an option to remove the image ...

... that is a neat little project for `hacktoberfest`

**Comment by Wiredframe** [comment]
Then let me add something for the event: Card layout 👍  :D

**Comment by y20k** [comment]
hacktoberfest came and went by. I am closing this issue. The "option to remove the image" is not planned for the foreseeable future.
