### ISSUE TITLE
issue with the following streams

### ISSUE THREAD

**Issue by erwanj** [y20k/transistor#151]
I can't add the 2 following streams  :
aspen : http://playerservices.streamtheworld.com/api/livestream-redirect/ASPENAAC
rock & pop : http://blaster.cdn.sion.com:1935/rockandpop/audioweb/playlist.m3u8

Is it something that can be easily fixed?

Thank you for the great app

**Comment by y20k** [comment]
> Is it something that can be easily fixed?

**Aspen** is an MPEG stream which advertised with the MIME tyoe `application/flv`. The stream seems to be wrong configured server-side. Sometimes streaming servers are configured wrongly - see for example [Issue 124](https://github.com/y20k/transistor/issues/124#issuecomment-299831920). Transistor always performs a MIME type check before starting playback. I do not want to remove that. So the only way to get this station to work is to contact the tech support of Aspen. I now that is not really an option in most cases. Sorry.

With **Rock and Pop** I am not sure. It is a HLS stream which is not officially supported by Transistor. Some HLS streams will playback fine, others won't. Anyway. I am probably doing one of the checks wrong, because it at least should download the station. **I will look into that.**
There is a quick fix. You could write your own m3u file and copy it into the directory `/Android/data/org.y20k.transistor/files/Collection`. The contents of this file should be:
```
#EXTM3U

#EXTINF:-1,Rock and Pop
http://blaster.cdn.sion.com:1935/rockandpop/audioweb/playlist.m3u8
```

Or you could just download this file here ([Rock and Pop.m3u.zip](https://github.com/y20k/transistor/files/1274171/Rock.and.Pop.m3u.zip)), unzip it and copy it manually into the mentioned directory.

**Comment by y20k** [comment]
HLS-streams link the **Rock and Pop** one can now be added via the Transistor UI. See [commit](https://github.com/y20k/transistor/commit/5c6fae90d2070dec79245f01b8940fa359c00154).

Thanks again for pointing me to this issue!! This feature / bug fix will be in the next release of the app.

I won't be able to make Transistor work with links like **Aspen** though. Sorry.
