### ISSUE TITLE
[request] option for Download/record

### ISSUE THREAD

**Issue by AhmedNazir** [y20k/transistor#156]
It is known, transistor app is a useful app.

But I think, it will be more productive if it has a Download/Recording option.

Thanks for creating this app. I wish, you will consider this request.

**Comment by y20k** [comment]
👍

I would like to have that feature, too. It would be great to be able to record a radio show that I often miss because it runs late at night.

But adding such a feature would make the app way more complex. Think of all the new screen that Transistor would need to get: 

- a tab that holds the recording schedules
- a date and time (start&end) picker with the option to make a schedule recurring
- a tab that holds your mp3 recordings
- a separate mp3 player for the recording
...

Transistor is just a fun project for me. But to be honest: I fear the amount of work it would take to implement this feature. So I think in the near future Transistor will not get a record feature. Sorry. 😞

**Comment by Cormak** [comment]
Since @y20k says Transistor probably won't get the feature, I'd like to recommend this project.

https://github.com/segler-alex/RadioDroid

I prefer the simplicity of Transistor because I can just paste in the few stations I listen to instead of relying on the radio-browser wiki, but this will let you record streams.

**Comment by qq278099550** [comment]
need record some news
