### ISSUE TITLE
[ Request ] Add an option for Search.....

### ISSUE THREAD

**Issue by AhmedNazir** [y20k/transistor#160]
I have 60+ radio channel in Transistor.
It's very annoying to find specific Radio.

**Comment by y20k** [comment]
Hi @AhmedNazir 

Thank you for your suggestion!! I need to think about this. 

We had a similar discussion about a possible feature to sort the list of stations a while ago. I did decide against it because I wanted to keep the app dead simple. 

So no surprise: My fist reaction would be to be against a search feature. But I understand that in your situation a search feature could be helpful. 

Although think about it:
* tapping a search button
* waiting for the keyboard to appear
* typing your search 

... that is not a good experience either.

As I said I need to think about it for a couple of days,

**Comment by rizapasha** [comment]
It is not request for searching for a new station I but i think is search within his added 60++ stations. I will support my server for station collections if you support for searching station URL

**Comment by rizapasha** [comment]
Sorry for my bad English. Miss understood. Yes It is annoying for typing. I am agree with you.

**Comment by y20k** [comment]
@rizapasha Transistor is at its core a very simple app. Just a list of station an a play button. I want to keep it this way, Sorry to disappoint you :-/ ... I do not want to have any server components. See this previous discussion about a similar topic: [work together?](https://github.com/y20k/transistor/issues/94).

**Comment by y20k** [comment]
I decided against a search feature. I know that you have a good reason for wanting this. But I come from the perspective that I want to keep Transistor very simple. I think in most use cases a search option is not necessary or cumbersome to use.

To better the user experience for users with long lists of stations I would go with an alphabetical fast scroller. The stock contacts app implements such a feature. 

I use the standard RecyclerView for the station list. It does not support [setFastScrollEnabled](https://developer.android.com/reference/android/widget/AbsListView.html#setFastScrollEnabled(boolean)) yet. But I guess that is only a question of time. 

I know that there are external libraries [(for example MaterialScrollBar, see below)](https://github.com/turing-tech/MaterialScrollBar) out there that provide alphabet-bubbles, but I would rather stay with standard android controls. So I will wait.

<img src="https://github.com/turing-tech/MaterialScrollBar/raw/master/sample.png">
