### ISSUE TITLE
Dark Theme [Request]

### ISSUE THREAD

**Issue by mrbatcop** [y20k/transistor#172]
Hi!
I really like your app but I think the dark theme (like details info in the app) will be much better because the white is really ugly especially the status bar. It's sad. (((
Please, make it or add the simple feature: change theme. 
Update: I mean the app background color = grey dark ; the status bar background color = red dark. I think it's the "true night mode" ;))))
Good Luck!

**Comment by y20k** [comment]
Hi there,

Transistor is supposed to be a very simple app. Just the basic features. The app subsequently has **no Settings screen** and it will probably will never get one. So there ist not much hope for an official Settings screen with a theme switch in Transistor.

That said. The Android system offers the option for an app to have a Day theme and a Night theme. A few weeks ago I found an interesting article on the topic: [AppCompat — DayNight](https://medium.com/@chrisbanes/appcompat-v23-2-daynight-d10f90c83e94). The post suggests that **the Android system will get a system wide setting for Night mode**.

My plan is to support that system-wide setting. The setting will probably come out in Android 9. Due to the nature of Android it will be a while until a significant portion of devices will run Android 9. For older devices thete will be a "secret" Night mode switch.

I will post any updates on that topic here.

**Comment by y20k** [comment]
# Current Night mode style

<a href="https://user-images.githubusercontent.com/9103935/36646700-84d44df2-1a7b-11e8-9c77-e4a990ee6792.jpg"><img src="https://user-images.githubusercontent.com/9103935/36646700-84d44df2-1a7b-11e8-9c77-e4a990ee6792.jpg" width="320" /></a>

<a href="https://user-images.githubusercontent.com/9103935/36646701-84ec7f12-1a7b-11e8-9cbd-2a231c4577f4.jpg"><img src="https://user-images.githubusercontent.com/9103935/36646701-84ec7f12-1a7b-11e8-9cbd-2a231c4577f4.jpg" width="320" /></a>

**Comment by mrbatcop** [comment]
Hi!
Oh! I didn't watch the closed issues at all (( - my bad :)
 Yes, Current Night mode style looks nice!
 But, I think if the status bar color will be the red it will be nicer!!! // of course, it is my personal opinion))
Thanks and Good Luck!

**Comment by y20k** [comment]
Dark theme is a hidden feature in the upcoming v3.0.4. You can activate it via long press on the three dots menu. I am still a bit hesitant to make this an official setting. Let's see.

**Comment by mrbatcop** [comment]
Dark theme is a hidden feature in the upcoming v3.0.4
=>
I have v3.0.5. It works great. Thanks man, that's cool!

Good Luck!

**Comment by Symbian9** [comment]
> You can activate it via long press on the three dots menu.

Great! In v3.0.9 it work like a charm!

Nice "eastern egg" ;-)
