### ISSUE TITLE
Ukrainian (cyrillic) characters shown in metadata as "ÐÐ¾Ð²Ð..."

### ISSUE THREAD

**Issue by Symbian9** [y20k/transistor#191]
On "PROMIN" radio some messages in metadata sting shown like on screenshot:

![screenshot](https://i.imgur.com/lKkEIiR.png)

Here is example of one of such metadata:

```
Новини Спорт Погода -
``` 

Stream URL:

- http://91.218.213.49:8000/ur2-aacp-ulow

In most cases, it should be Ukrainian letters.

**Comment by y20k** [comment]
Hi there. Thanks for reporting this issue. Right now Transistor only supports UTF-8 and Latin1 (see also Issue #188). 

* Any Idea what format the specific metadata has? 
* Is only one station impacted, or is this a wider problem?

**Comment by evgentset** [comment]
Hi, that metadata has "Cp1251" encoding which displayed incorrectly in UTF-8. Idk how to detect encoding page in metadata, but as workaround this issue can be fixed by change line 377 in Station.java (
https://github.com/y20k/transistor/blob/f2b65e6e0a6ccff33d2ef26fd2e0e790cd76c4bb/app/src/main/java/org/y20k/transistor/core/Station.java#L377) 

Need to change this line to something like:
`BufferedReader br = new BufferedReader(new InputStreamReader(inputStream, "Cp1251"));`

But it may work incorrectly for another radio stations which use another codepage. So I suppose right way is detect  codepage before reading metadata somehow.

**Comment by y20k** [comment]
Okay. I will look into it. Thanks.

**Comment by y20k** [comment]
Hi there,

I changed the way metadata gets extracted from radio streams. As a side product this seems to have resolved the issue with cyrillic characters.

![Screenshot_1561895355](https://user-images.githubusercontent.com/9103935/60396187-34f10880-9b3e-11e9-8ecb-2a20d30a0371.png)


I have an official test version for the next release of Transistor. If you are interested head over to #225.

**Comment by Symbian9** [comment]
> I have an official test version for the next release of Transistor.

Thanks! I will test it and if there would be no such issues will close this issue thread.

**Comment by y20k** [comment]
I hope that [v3.2.1](https://github.com/y20k/transistor/releases/tag/v3.2.1) solves the issue. If not please re-open it.
