### ISSUE TITLE
feat: add a scrollable list/index of scraped m3u playlist sources

### ISSUE THREAD

**Issue by niftylettuce** [y20k/transistor#198]
Or we can recommend something in the app for a directory of m3u streams?

Or perhaps a popular/favorite list sourced from Reddit?

**Comment by y20k** [comment]
Hi @niftylettuce. 

Thanks for your suggestion, but I do not have any plans to integrate a radio directory into Transistor. Sorry. See also: #94 

Mainly because I want transistor to be a completely stand-alone app. I do not want it to rely on libraries and services I do not control.

We could link to suitable starting point for search in the README.md or in the Wiki here.

**Comment by ShadyGaDa** [comment]
These two best I've found.
http://www.radio-browser.info/gui/#/bylanguage/english

http://www.radiosure.com/stations/

**Comment by y20k** [comment]
If you would like to, you can create a new wiki page here with those links. (not sure if your account is allowed to)

**Comment by y20k** [comment]
> And while you're at it, could you please fix loading .pls links from this site, like this one: http://www.radio-browser.info/webservice/pls/url/105443

This looks on the face of it like a server configuration error. The MIME type Chrome reports is `application/octet-stream` (so does Transistor's error dialog). So the issue might be related to #101. But on the other hand maybe Transistor cannot handle the redirect from http://www.radio-browser.info/webservice/pls/url/105443 to http://www.radio-browser.info/webservice/pls/url/105443/radio.pls?

**Comment by pelya** [comment]
A lot of servers mark .pls and .m3u files as application/octet-stream. We
can infer the file type from file extension most of the time, in either URL
or in Content-Disposition HTTP header.

**Comment by y20k** [comment]
@pelya Good idea!! I implemented a `Content-Disposition` [lookup](https://github.com/y20k/transistor/commit/a4eee7225b4d667ff5c234ccab27c7d3356d7cb1) for files of type `application/octet-stream`. I do not want to broaden this lookup to ANY file type. But doing this for application/octet-stream seems reasonable. Thanks.

**Comment by y20k** [comment]
[v3.1.0](https://github.com/y20k/transistor/releases/tag/v3.1.0) is out. It improves the handling of links from radio-browser.info. Additionally I did a add a section "[Places to look for radio stations](https://github.com/y20k/transistor/wiki#places-to-look-for-radio-stations)" in the Wiki and added a link to this section in [README.md](https://github.com/y20k/transistor/blob/master/README.md). 

I am still reluctant to add anything (even a link) in the app itself. 

This issue is basically a duplicate of #68 which itself already closed and linked to in [Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48). It is safe to close this one, too. 

Thanks for participating in the discussion. And sorry that I could not help you. If it helps: The discussion made Transistor better - just not in the way you suggested.
