### ISSUE TITLE
Save multiple streams as a single station

### ISSUE THREAD

**Issue by steelman** [y20k/transistor#206]
Some stations publish lists of their streams as M3U playlists. Oftentimes streams on the lists have the same content at different bitrate. Sometimes URLs on the lists change in time and/or "space". For example to connect users to the closest transmitting server. This is how things might work

1. A user inputs playlist URL when adding a station.
1. Transistor downloads the playlist, saves a list of stream URL-s **and** the playlist URL as a single station.
1. The user chooses a stream to play.
1. The stream is marked as default.
1. Next time user tunes in the station, the default stream is played.
1. The user can choose to play a different stream from the list.
1. The user can reload the playlist to get an up to date list of streams. If the default stream is not present on the new list, the user is required to choose a stream again.

Having the same station at different bitrates for different situations (e.g. mobile connectivity vs wifi) as a single item on the list of stations seems more convenient than having two separate stations.

**Comment by y20k** [comment]
Hi @steelman, 

I think this would be a nice feature. A good place to select streams would be in the pull-up sheet below the playback controls.

But while it sounds like a small thing, it implies a lot of changes under the hood. I am at the moment a bit time constraint, so that I cannot implement it. I will add the label `help wanted`to this issue.

**Comment by y20k** [comment]
I am closing this issue since I am not going to work on it in the next couple of month. 

I did feature the request in [Previous discussions and feature requests #readmefirst](https://github.com/y20k/transistor/issues/48) and in [CONTRIBUTING.md](https://github.com/y20k/transistor/blob/master/CONTRIBUTING.md) to encourage other to help me out here.

Sorry & Cheers
