### ISSUE TITLE
Autostart a radio station

### ISSUE THREAD

**Issue by dropdrop20** [y20k/transistor#207]
I want to blindly start  Transistor with AutoStart (AutoStart No root_v2.2) and have a choosen station run. Unfortunately Autostart will start only applications not shortcuts on my  phone launcher.

It's possible to add it?
If to much work, can you please give a diff to just hardcode for my own purpose  a station?

**Comment by y20k** [comment]
Sorry for answering so very late! 

I don't know AutoStart. But if it supports starting an app with Intent Extras, you might want to have a look here: [Useful ADB commands](https://github.com/y20k/transistor/wiki#useful-adb-commands). 

There are definitely automation apps out there that support Intent Extras. Tasker (which I do not have in use currently) does support Intent Extras (see this [Guide](https://forum.xda-developers.com/showthread.php?t=2489449) for example). 

> It's possible to add it?

No. Sorry. An option to have Transitor to start playing when you restart your phone, is a quite unusual feature IMHO. Also Transistor has no settings screen and will not get one in the foreseeable future, because I am trying to keep the app super simple -  ... for my own sake, actually, since I do not have too much time to work on it at the moment.

Cheers
