### ISSUE TITLE
POLL: Should Transistor leave Google Play?

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#219]
A couple of month ago I installed [LineageOS for microG](https://lineage.microg.org/) on my phone.  LineageOS for microG is an Android distribution that comes with the [F-Droid](https://www.f-droid.org) store preinstalled. I must say, since I was using mainly Open Source apps before, I really did not miss the Google Play Store much. That made me think: Should I pull Transistor from Google Play. I personally like [F-Droid](https://www.f-droid.org) a 1000 times better than Google Play. F-Droid for me is by far the better home for my app.

I am interested in your thoughts ...

**Comment by JonnyTech** [comment]
Ditto on your comments - I have not used Google Play Store in years - people can grab the app from F-Droid or the GitHub release pages.

**Comment by blausand** [comment]
That decision is of a higher scope, i think.
I'm not using _Google_ at all (not even GSF), so i'm pretty pissed that many apps, even publicly funded ones aren't published outside _Play Store_.

As a means to keep apps updatable, a **repository model is favorable to publishing APKs directly** on the net and the _F-Droid_ client is by far the best choice here since you can add third party repos.
On the other hand, publishers will not invest in solutions **without any billing model**.
Another problem here is that in order to publish on _F-Droid_'s repo **requires opening their sources**; in many cases, **authors rely heavily on closed-source frameworks**.

I keep writing authors about releasing their apps outside _Play Store_ and getting rid of closed source dependencies, which will eventually end up in the portfolio of global players who will subsequently abuse them to commercially collect user data.

**So to answer your question: Bear in mind that you might loose a lot of user base in the beginning, but to boycot _Play Store_ (and other commercial gate keepers) helps establishing a culture of free trusted repositories.**
### I'd say: "YES, let's get the hell outta there. Tell the others!"

**Comment by ainola** [comment]
The benefit of the play store is that it has is a much wider audience. If you're fine with losing discoverability with most of the general population then I'd say go for it. Mobile app stores are poison.

**Comment by nowster** [comment]
The Play Store version seems to be the only one that works with Android Auto.

**Comment by Pentaphon** [comment]
@y20k No. Keep it there. The Play Store needs more open source apps like yours.

**Comment by y20k** [comment]
> The Play Store version seems to be the only one that works with Android Auto.

A valid argument.

**Comment by JonnyTech** [comment]
What can be done to make the fdroid build work with android auto?

**Comment by y20k** [comment]
> What can be done to make the fdroid build work with android auto?

As far as I know: Android Auto will only run apps that are certified to run. An app gets certified for Auro during the Play Store app submission process. So I think: F-Droid apps will never run on Android Auto.

**Comment by 532910** [comment]
Not all people have (or are able to install) F-Droid. So while it's not complicated for you to put in on GPlay, please put in on GPlay.

**Comment by y20k** [comment]
Thanks for participating. I will keep Transistor on GooglePlay. Although I do not like GooglePlay, it does not hurt to have the app there.

**Comment by nowster** [comment]
I, for one, would greatly miss being able to use it with Android Auto.

**Comment by blausand** [comment]
I immediately read the article you're linking. 
Follow me on Twitter to learn what i think about it.
As the developer of Transistor you shouldn't waste any energy on broken architectures.
Android is about to become a fossil since a couple of years already. I'm looking forward to see something less fucked-up.

**Comment by y20k** [comment]
I checked out you twitter account.

In one of your tweets you wrote: 

> __Listen, Google. A private key outside my infrastructure can't be called "my key" anymore.__

I am 100% with you.

**Comment by radasbona** [comment]
Just for the record:
My Work Phone has a locked Installation from Unknown Sources. (And adb and so on)

So PLEASE - stay in playstore.

**Comment by y20k** [comment]
A short update on this topic.

- The Google Play version of the app will receive no further updates beyond v4.0.18 (see [releases](https://github.com/y20k/transistor/releases))
- On Google Play the app is not visible for new users anymore. User who already own the app, can still download v4.0.18.
