### ISSUE TITLE
Does not support audio URLs

### ISSUE THREAD

**Issue by antoniocosta** [y20k/transistor#22]
Such as...
http://streams.kqed.org/kqedradio
or...
http://broadcast.infomaniak.ch/radionova-high.mp3

Can the URL parsing be made a bit more resilient?

**Comment by maurete** [comment]
+1 for this.

Meanwhile, i worked around the problem by manually creating m3u files and placing them in the appliication's own "Collections" folder as suggested in the About... information. Worked like a charm.

**Comment by y20k** [comment]
Thank you for reporting this! I am a bit hesitant to call this a bug. The app is working on purpose with m3u or pls links only. 

For a longer explanation see #6. The short version is: Transistor only parses URLs. It does not test them. If I opened up the app to all kinds of links I expect people to throw in all kinds of links. For example to http://www.kqed.org/radio/listen/ instead of  http://streams.kqed.org/kqedradio .

All I can do for now to make the fact that Transistor needs playlist files more obvious in the UI and in the error messages.

**Comment by antoniocosta** [comment]
Agree it shouldn't be called a bug... but wouldn't it be simple to just check the http response header for Content-Type, and create the playlist if it's audio?

**Comment by y20k** [comment]
Okay. A good idea. I will give that a try. But expect delays, since I do not have a lot time on my hand right now. Thank you!

**Comment by antoniocosta** [comment]
Awesome! Not in a hurry. Thank you!

**Comment by meonwax** [comment]
Hello,

Nice project!
I forked the code and i'm currently working on an implementation of adding plain audio files.
Will send a PR once i think it is working correctly.

**Comment by y20k** [comment]
:+1:

**Comment by y20k** [comment]
My last comment was a bit brief :-) - so the longer version of :+1:  would be: Thank you for giving it a shot. I am looking forward to your solution. Please contact me in advance if your solution demands any changes in the UI.

**Comment by meonwax** [comment]
Here is the pull request: #35 
Tell me what you think about it.

Sorry, i messed up the git merge history a bit as i was not fully aware of syncing a forked-repo with the upstream one.

**Comment by y20k** [comment]
Your code works very good, as far as I was able to test it. I now need to adjust some of the strings within the UI.

Thank you for contributing!!

Speaking of: I would like to add you as a contributor to the [AUTHORS.md](https://github.com/y20k/transistor/blob/master/AUTHORS.md). Is that okay? Or do you prefer any other form of getting credit?

**Comment by meonwax** [comment]
You are welcome.
I will dig in some other small issues that i have found soon.

Adding me to *AUTHORS.md* is fine. Thank you.

**Comment by y20k** [comment]
Okay. Good to know I was adding a fix just a minute ago. In some circumstances there are still crashes.

**Comment by meonwax** [comment]
Btw: you do not like a `.gitignore` ?

**Comment by y20k** [comment]
Ups. That was a mistake. I had local copies of .gitignore files which were not managed by git and thus not part of the repo. They caused a conflict, which I apparently fixed by deleting. Will re-upload them.

**Comment by meonwax** [comment]
Ok fine.
Could you update the documentation that says that only streams within`.m3u` and `.pls` files are supported?

Should we support other content types like *wma* `audio/x-ms-wma`?
I think there is also *asx* that acts as playlist container for *wma* files.

**Comment by y20k** [comment]
Yeah. Okay. I will update the [README.md](https://github.com/y20k/transistor/blob/master) and [strings.xml](https://github.com/y20k/transistor/blob/master/app/src/main/res/values/strings.xml) before the next official release.

**Comment by y20k** [comment]
I am a bit reluctant to "officially" support ASX/WMA since I had an issue (#7) here with WMA (over rstp). Also AAC (#19) seems not to be working on all ROMs. That why I did not plan to support any new formats.

But I do not want to discourage you from trying! If you can get any additional format to work without the need to switch to another Playback library ... that would be great.

**Comment by meonwax** [comment]
I think you can close this and i will open a new enhancement issue for supporting WMA streams.
