### ISSUE TITLE
Please add support radio station site

### ISSUE THREAD

**Issue by CryptAnalitic** [y20k/transistor#226]
Hello, y20k !

Please add support radio station site :
http://www.radio-browser.info/

This site support link on 24521 internet radio stations

**Comment by y20k** [comment]
Hi @CryptAnalitic 

thanks for your suggestion!! Can I refer you to the following issue: [work together? #94](https://github.com/y20k/transistor/issues/94) - and the linked issues there (#114, ...) ?

Short version: I was (and still am) considering an integration, but I am probably not going to implement it, because:
1) I do not have the time
2) I am skeptical when it comes to rely on third parties - libraries and (in this case) web services.

**Comment by CryptAnalitic** [comment]
Hi @y20k  !

This service is open source :

> > Free for ALL! 
> Everyone can use this station board in their software freely. Just have a look at the API documentation. 
> Everyone is free to use the collected data (station names, tags, links to stream, links to homepages, language, country, state) in their works. 
> I give all the rights I have at the accumulated data to the public domain. 

Open source support open source
-------------------------------------------
_1.I do not have the time_

:^( Badly

Best regards,CryptAnalitic
