### ISSUE TITLE
Add Next/Previous KeyEvent for non Android Auto

### ISSUE THREAD

**Issue by jamal2362** [y20k/transistor#227]
Hello,

I own a Android Head Unit (MTCE) device for my car and ask for a feature.

Is it possible to implement KEYCODE_MEDIA_NEXT and KEYCODE_MEDIA_PREVIOUS into the App?

When I use my steering wheel control in car to press up or down in other apps, it automatically jumps to the next station or back.

Could you try adding it?

Thank you for the great work!

Best regards,
Jamal2362

**Comment by y20k** [comment]
Hi there, I did try to implement support for Next/Previous buttons on headphones. I did not work out. See: https://github.com/y20k/transistor/issues/89#issuecomment-397285861
I think enabling this feature on a Head Unit will run in the same problem.

**Comment by jamal2362** [comment]
Thank you for the Reply!

I have spend more than 20 hours to get it to work without any success.
Thats why i open an issue, because i need your help.
I hope there is some way for it to work, I think there are missing codes in the PlayerService

Sorry for my bad english.

**Comment by y20k** [comment]
It has been a while since I looked at this. But as far as I can see: The `StationListProvider` in the playback service needs to be initialized for the Skip feature to work. And `StationListProvider` only gets initialized when connected to Android Auto. 

Since you are using a Head Unit, maybe the `PackageValidator` does not recognize the HeadUnit. Do you see the message "OnGetRoot: Browsing NOT ALLOWED for unknown caller." in LogCat? If so adding the Head Unit's cert needs to be added to [allowed_media_browser_callers.xml](https://github.com/y20k/transistor/blob/master/app/src/main/res/xml/allowed_media_browser_callers.xml). 

But that is just a guess. Let me know if you succeeded. I am interested in your solution.

**Comment by jamal2362** [comment]
This message is not displayed in Logcat!
There is not according to Log!

So the car radio is like a Smartphone/Tablet from the system...

If I want to trigger a key in the terminal no matter if smartphone or car radio, with the command "input keyevent 87 and 88" he can go to the next station with other apps, but not with this app.

How do I create a cert?

Here a picture from my Radio with the Application for understanding what i mean :)

https://abload.de/img/156466703823487106149iejgu.jpg

**Comment by y20k** [comment]
Ah interesting. You setup looks like as if table was built into a car. Then we are back to the point where I was [last year](https://github.com/y20k/transistor/issues/89#issuecomment-397285861) :-/ 

The Skip feature I implemented for Android Auto (see below) relies on the `StationListProvider` to be initialized. BUT the `StationListProvider` is only used in car-mode. You are using the app in normal / phone mode.
 
The problem here is the playback service was originally built just as a player for a single station. It has no knowledge of all the other stations that the UI of the app has. (The Android Auto with the StationListProvider feature were built-in afterwards.) That is why the app crashes when trying to skip when not connected to a car. The car part of the app has not been initialized.

Anyway. Adding this feature is more work than I am willing to put into the app at the moment. That would be a change in how the app is "architected". Transistor is just a fun project for me and I do not have a lot of time to spare - sadly.

![Screenshot_20190801-154954](https://user-images.githubusercontent.com/9103935/62298871-2a46cd80-b474-11e9-92fc-418f535cb544.png)

**Comment by jamal2362** [comment]
The only thing that works on the head unit/smartphone is to start or stop playback with the app.

That's not a problem, so I asked if it might be possible to add it.
If this is not so easy then it is not a problem.
I thank you for what you have done so far. :)

**Comment by grrosminet** [comment]
Hi

I  have a simple BT connection on my car and have the same problem. I have found how to fix it, but there are some points that needs to be changed in my solution.

[my patch](https://github.com/grrosminet/transistor/commit/d4e6ead1a2cf6a6bddc311b6d8adbad73113b310)

Explanation : 
- the essential of the patch is the overriding of  onMediaButtonEvent . As I don't have AndroidAuto, I have not tested if it breaks something on it.
- the second part of the patch is that onLoadChildren is never called without AndroidAuto, so stations provider remains empty. That's why I have initialized it in the onCreate method, but I fear it's a bad solution.

**Comment by grrosminet** [comment]
I didn't mention : this also fix prev/next buttons in the lockscreen media player widget (when misic is playing and you swipe the clock)

**Comment by jamal2362** [comment]
Hi,
Is it only working on the lockscreen widget ?

**Comment by grrosminet** [comment]
Hi, 
In my case, this patch makes prev/next work with BT headset, with BT car and with lockscreen widget. But there is a lot of testing to do before it can be provided in production release

**Comment by jamal2362** [comment]
I have compiled the app with your fix and it's working fine now on my (MTCE) Head Unit.
My CanBus decoder on my car reconize it correctly now and prev/next works now and on BT too.

and i have test it with the Terminal App from the Play Store and trigger the keyevent with this code: 
"KEYCODE_MEDIA_PLAY_PAUSE" --> input keyevent 85
"KEYCODE_MEDIA_STOP" --> input keyevent 86
"KEYCODE_MEDIA_NEXT" --> input keyevent 87
"KEYCODE_MEDIA_PREVIOUS" --> input keyevent 88
and this working fine too.

Thank you for your help to fix this issue, now the app is perfect for me :)

**Comment by y20k** [comment]
v4 supports previous and next actions
