### ISSUE TITLE
select the deletion option and cancel it will unexpectedly cancel the sleep timer

### ISSUE THREAD

**Issue by tingsu** [y20k/transistor#235]
Hi, I feel this issue is a little annoying, if fixed, will improve user experience a lot.  I detail this issue as follows.

- I have searched the history issue list, and have not found similar issues. 

- The issue was found in the latest release version 3.3.2 from Google Play (this version is also the latest code commit), and were reproduciable on both a Google Plxel 3 and an Android emulator 6.0 device.

- Issue 

Scenario 1

1. When a station is playing, click the sleep timer to start the timer (the timer starts, correct!)

2. select the ``Rename`` option and cancel it (the sleep timer is still there and correctly counting down, correct!)

3. select the ``Delete`` option and cancel it (the sleep timer is unexpectedly cancelled, why?). This is strange that this ``noop`` action affects the timer.

- Reproducing video

![20191020_233823](https://user-images.githubusercontent.com/3156978/67166952-c35ef380-f394-11e9-91d4-07baea83b9ec.gif)

Scenario 2

1. When a station ``A`` is playing, click the sleep timer to start the timer (the timer starts, correct!)

2. Switch to another station ``B``, which is not playing now (the timer is still there and counting down, correct!)

3. Select the ``Deletion`` option of station ``B`` and cancel it. Now, the timer is unexpectedly cancelled. It is strange because this ``noop`` action does nothing related to the station ``A`` where the timer was initially set.

- Reproducing video

![20191020_233802](https://user-images.githubusercontent.com/3156978/67166957-cb1e9800-f394-11e9-88e4-e5da9d2b58c9.gif)

**Comment by y20k** [comment]
This behavior is not really an error. Let me explain. 

First the sleep time is always cancelled, when you stop playback. The main problem is: Playback needs to stop in this app, when you try to delete a station. The reason is an weakness in the main architecture of the app, that bytes me here and in some other places (e.g. Android Auto), too. The background service that plays streams and the UI that manages the stations do not share a common understanding about the state of the station list. Basically it is never really safe to assume that the station you are about to delete is NOT the station playing right now. Therefore it is safer to stop playback before a delete action.

This issue is fixable. But since the root is so deep in the apps architecture, I do not intend to fix it in the forseeable future. Sorry. The needs to wait for the big Kotlin re-write, that eventually needs to come.

**Comment by tingsu** [comment]
Thanks for your detailed explanation, @y20k . I can understand the complexity if fixing this issue. Yep, the asynchrony between the background service and the UI reallys do bring some trouble, and I can foresee the effort to fix this issue will be large if adjusting the architecture. Then let's temporarily just keep this for now.
