### ISSUE TITLE
Fetature request: Organising stations by Labels 

### ISSUE THREAD

**Issue by Bullenwaechter** [y20k/transistor#255]
Hi there
Thanks for your great work and this really fine app.
A possibility to organise stations by lables would possibliy be a upgrade for Transistor app.
For example to sort the stations per genres or personal notes such as: Metal, or ProgRock, Pop or ....

This is one of the view features I really miss on Transistor so far....

**Comment by y20k** [comment]
Hi.

I am currently rewriting the app from scratch (see #251). The new version of Transistor will have a couple (but not many) interface enhancements, that I think are still within the spirit of the app. The only planned feature that would help with organizing your radio station list will be: You can favorite a station.

Your suggestion would go further: An an open/user-defined tagging system... Implementation-wise that would introduce new UI elements / workflows: 1. Adding/Editing/Deleting tags 2. Sort-Button and Sort-State indicator. Since I want to keep the app super simple, I think my answer would be no here. Sorry.
