### ISSUE TITLE
Docu: setup build environment

### ISSUE THREAD

**Issue by tiborroald** [y20k/transistor#257]
Please put a minimal set of instruction to setup the build environment.
Something like.
git clone ...
export ANDROID_SDK_ROOT=$HOME/Library/Android
chmod +x ./gradlew
./gradlew build

Anyway I've installed SDK:
$HOME/Android/tools/bin/sdkmanager  --sdk_root=$HOME/Library/Android  --install 'platforms;android-23'

But:
 - lint complain about translations
 - lint complain about API calls not in API 23
- disabling lint and building the APK, it still give generic error at install
Tested on Android 6.0 tablet.
Your built APK on the Github it's working. 
So I would want to have my build env setup and start to hack a bit.

**Comment by tiborroald** [comment]
Very interesting! The APK was installed over USB (via adb)

**Comment by y20k** [comment]
Actually I am always just building the app using Android Studio. I do not feel competent enough to put up instructions :-/ I thought once one knows how to compile one Android project, it should be the same for any other app. 

The app has been developed under the assumption `minSdkVersion 25`. Maybe you trying to compile it for older devices makes it more complicated.

**Comment by tiborroald** [comment]
Thanks for the help! Anyway, avoiding lint was the workaround.
And using midSdk = 23 + targetSdk=23

**Comment by y20k** [comment]
I also got a lint error. But only when I created a signed built of the type release. The error was caused by a string, that was translated, even though it was not present in the default language. I deleted this string (see [commit](https://github.com/y20k/transistor/commit/9a0bafe8c3d9f859ecefd56996b142a40c88827b)).

If that was the error you got, you can leave the lint check turned on in the future.
