### ISSUE TITLE
Station is not valid

### ISSUE THREAD

**Issue by JonnyTech** [y20k/transistor#260]
Trying the new v4 test. Manually copy/pasting stations from old format. But most show `Station is not valid` upon import. Is there a specific format that should be used?

**Comment by y20k** [comment]
Hi @JonnyTech 

Transistor should auto-import old stations - in theory. In practice one condition needs to be met: The old and the new Transistor need to be signed with the same certificate. In that case the app installs as update rather than a new app. The F-Droid version is signed with the F-Droid certificate, the one from GitHub (and PlayStore) is signed with my certificate. So for an update install - which will be the default case I presume - there should be no need to manually copy over stations. To test this you can do the following.

1. save the contents of the folder `/Android/data/org.y20k.transistor/files/Collection`
2. install the latest [GitHub release](https://github.com/y20k/transistor/releases/tag/v3.2.4)
3. copy back the contents of the Collection folder
4. install the latest [test build](https://github.com/y20k/transistor/issues/251) for version 4

You stations should be copied over.

Anyway. I am **interested in what you exactly did**, when you tried to copy over stations manually. 

You wrote 

> "But most show `Station is not valid` upon import."

So some stations could be imported while others failed right? Could you post an example of a station that failed to be added?

**Comment by JonnyTech** [comment]
Thanks for the reply @y20k. Yes, I am coming from a f-droid build and had backed-up and restored the `Collection` folder as a matter of course in order to get your self built version installed.

A couple of points to note. Transistor v3's folder was named `Collection` whereas v4 uses `collection` (note the capitalisation). When launching v4 it would wipe out the v3 folder and replace it with a new empty v4 one.

Once I noticed this, I copied the contents of the folder and not the folder itself. Launching v4 creates and populates an `images` folder correctly ie lots of subfolders with GUID type names containing files named `station-image.jpg` and `station-image-small.jpg` with valid image contents. There is also a `collection.json` file in the `collection` folder containing just this one line: `{"modificationDate":"5/12/20 10:00 PM","stations":[],"version":0}`. The existing v3 files are untouched and the app shows no stations.

Then I tried to add the stations manually by opening the v3 `.m3u` file and copying the stream name from there and pasting it into v4's `add new station` dialog.

An example that worked: `http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p` and one that did not: `http://media-ice.musicradio.com:80/RadioXLondon`. I don't know if these are region locked and the may only work in the United Kingdom.

All stations work correctly in v3. I am running Android 10, if that helps.

**Comment by y20k** [comment]
@JonnyTech 

**# auto-import**
I actually until now never did a real world test of this feature yet. To my defense :smiley: the app is not release ready. Anyway. Thanks to your feedback :+1: I now know what to test for. You are probably right the different spelling of collection might be the problem here.

**# station not valid**
Not all audio formats that v3 supports are supported in v4 yet. Your example of a non-working station is an AAC stream. I will see to bring that feature back. :+1:

**Comment by y20k** [comment]
After reviewing my own code, I remembered: The code, that I was using in the Import routine, was just a test to see, if I can read in old stations. It did not really import any stations at all.

So now I completed the import routine. And the above described steps actually work.

1. save the contents of the folder `/Android/data/org.y20k.transistor/files/Collection`
2. install the latest [GitHub release](https://github.com/y20k/transistor/releases/tag/v3.2.4)
3. copy back the contents of the Collection folder
4. install the latest [test build](https://github.com/y20k/transistor/issues/251#issuecomment-628044176) for version 4

Sorry, that I misled you. I could not remember anymore, how far I got with the importer. I also enabled AAC playback(*). I hope that importing your stations now works again.

(*) HLS playback is not working at the moment.

**Comment by JonnyTech** [comment]
Superb, the import now works! Thank you. No need to apologise, it is beta and I am happy to help provide feedback.

Some `.aac` streams now work, some do not although they are listed. I assume they are `hls`, an example is `https://ais.absoluteradio.co.uk/absoluteradiomed.aac`. Is there a way to check what type it is?

**Comment by y20k** [comment]
> `https://ais.absoluteradio.co.uk/absoluteradiomed.aac`

VLC does not play this address and the old Transitor does not, either. At least for me. :-/

**Comment by JonnyTech** [comment]
It is only available in the UK. Transistor v3 plays all stations from that provider correctly for me. Website states UK only too (https://listen.absoluteradio.co.uk/). How can I check from my end what the problem is?

**Comment by y20k** [comment]
What does v3 Transistor display under "Media type" during playback?

**Comment by JonnyTech** [comment]
The stations went offline and now have returned. Odd is that their address changed: `http://ais.absoluteradio.co.uk/absoluteradio.mp3`. Works in both v3 and v4. Great job, thanks again!
