### ISSUE TITLE
v4: swiping

### ISSUE THREAD

**Issue by JonnyTech** [y20k/transistor#267]
In the v4 interface I accidently swiped the screen which deleted a station because by bad luck my knuckle landed on the button to confirm deletion. Can you add an option to configure or delete swipe gestures, or to archive rather than delete a station?

**Comment by y20k** [comment]
I think the concept "Archive" or for that matter "Trash Can" is not common for media apps. That plus the resolve to keep the app simple and the settings screen minimal lead me to say no to your suggestion.

I hope that you just had bad luck and that the current workflow for removing radio stations is not error prone. Your feature request alerted me here. I need to keep an eye on that. I could move the delete action into the drop down menu. But for now I like the swipe gesture :-)

**Comment by frictionlessmeme** [comment]
Just would like to add my two cents to this, in the spirit of feedback, since this is something you've said you should keep an eye on.

I really like the Transistor app and am very grateful for all the work you do on it - over the last few years it has been an ideal app for listening to radio streams which does exactly and only what was necessary.

Unfortunately I am finding the new design choices to make the app unusable for me. Whereas you used to be able to listen to a station with the long-press action, now you have to press a small play button on the right of each listed station.  I can confirm that it is a very error prone setup for me. Pressing this button works for me about 60% of the time, the rest of the time it initiates a swiping action, and if I don't notice this in time and keep my thumb held down and slowly return it to its place, the item just slides off the screen, initiating an action I didn't intend - I've had numerous accidents with my station list, not only accidentally deleting stations, but also accidentally favouriting them. This is of course reversible but abruptly moves the station I wanted to listen to off screen to the top of the list. This means it is still an annoyance and I would describe it as a bug. It happens a lot, and really impairs my use of the app. Of course I could be instructed to use the app more carefully, but honestly this raises the bar so high for using this app that I might as soon just stop using it - or try only to use it through station-specific shortcuts.

I also do not understand the utility these changes add. Adding stations has historically been the most irritating aspect of using the app - the necessity of hunting down live radio streams and adding them meant that it took a good bit of work to build up a list of all of the stations you like. You've successfully reduced the overhead on this task with the search function and this is very welcome. However, once the stations are in your list, presumably those are also your "favourite" stations. I can see why you might want the option to re-order them according to preference rather than alphabetical order, but I do not see why "favouriting" specific stations (from a list that exists already entirely as a result of your own preferences) is so essential a feature that it has to use so immediate a user action as a swipe action. Likewise, deleting a station by swiping the other way, even with a confirmation, raises the probability of an accidental deletion too high. Even with the new search-to-add function, it is still a bit of work to build a list of stations, so it is an irritant to see them disappear unintentionally, and have to spend time re-adding them. 

As a general UI point, having a long list of radio stations is a USP of this app for me, but making it so that every item on that list can so easily slide left or right makes it feel less like a permanent list and more like a notification tray - it makes it feel ephemeral and unstable. I derived a sense of comfort - having gone to the work of assembling a list of streams - from the sense of stability of the list in previous versions of the app. This is now gone. You spend so long getting your eggs in a row, and then a tiny user mistake can set them all rolling off in different directions again. As I say I love this app and appreciate it, but it is an honest report of my experience that using it now makes me feel tired and irritated and cranky. The changes mystify me. The vertical padding between the items in the list - presumably implemented to mitigate accidental swiping of the wrong item - also devours vertical space and diminishes the utility of the list.

**Comment by y20k** [comment]
Hi @frictionlessmeme , thank you for your feedback. I am considering to drop the swipe to delete gesture together with the drop down menu in favor of an edit screen (see also #279). I need to sketch out the ui, to see if that would work out. Since Transistor is a hobby project of mine changes like this tend to take a while.
