### ISSUE TITLE
HLS stations no longer work after update

### ISSUE THREAD

**Issue by nowster** [y20k/transistor#272]
Stations which use HLS (eg. BBC) no longer work in Transistor after the Kotlin update. They worked with the previous version.

Have copy-pasted the URLs to Chrome, and they're playing fine there.

**Comment by JonnyTech** [comment]
BBC works for me, been listening to Radio 2 all day: http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p

**Comment by y20k** [comment]
Could you paste an example URL? I will look into this.

**Comment by nowster** [comment]
BBC World Service:

http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_vlow/llnw/bbc_world_service.m3u8

Radio Jackie:

http://media.radiojackie.com/redirector/livestream.m3u8

**Comment by nowster** [comment]
> BBC works for me, been listening to Radio 2 all day: http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p

That's an MP3 stream at 128kbps. The BBC provides AAC and AAC+ format HLS streams at rates between 48kbps and 320kbps. See http://www.radiofeeds.co.uk/other.asp

**Comment by y20k** [comment]
@nowster 

BBC World Service and Radio Jackie both do not work. Each for a different reason. 

- Radio Jackie sends the MIME type metadata in an unusual capitalized way
- Transistor does not detect BBC World Service as HLS

Gladly both issues are easy to fix.

**Comment by y20k** [comment]
I published a quick bugfix update - [v4.0.1](https://github.com/y20k/transistor/releases/tag/v4.0.1). It solves the issues and should appear on Google Play and F-Droid soon.

**Comment by JonnyTech** [comment]
Ah, so to go from MP3 to AAC/HLS, is it possible to edit a station URL without having to delete and re-add it?

**Comment by y20k** [comment]
There is no option to change a stream address in the user interface of the app. This is somewhat on purpose, because most users will have a hard time to understand the difference between a playlist container file and the actual stream address that is in those playlist files.
You could edit the collection.json file in `Android/data/org.y20k.transistor/files/collection/`. But you should make copy before doing so :-)

**Comment by jpds** [comment]
On v4.0.1, I cannot play the AAC streams from: http://www.radioswissclassic.ch/de/empfang/internet

I recall that these worked on the v4 betas.

**Comment by y20k** [comment]
Hi @jpds 
the problem with the aac streams is basically #278. A MIME type check on the wrong URL. This is fixed in [v4.0.2](https://github.com/y20k/transistor/releases/tag/v4.0.2), which is available on Play Store and will be soon on F-Droid. Sorry for the inconvenience. You may need to "Update" the station that causes problems from the station options menu.
