### ISSUE TITLE
M3u streams are not yet supported by ExoPlayerLib

### ISSUE THREAD

**Issue by stefanhh0** [y20k/transistor#278]
See description here for all the details here, it should contain everything: https://github.com/google/ExoPlayer/issues/7605

See as well: https://github.com/google/ExoPlayer/issues/4066

It used to work fine on pre v4.

**Comment by y20k** [comment]
Hi @stefanhh0 

you found a very important bug!! Thanks. I will publish an update this afternoon.

**Comment by y20k** [comment]
The problem you found was not related to ExoPlayer, but to a mime type check that was performed on the wrong address. All manually added stations since v4.0.1 were affected.

I just published an update ([v4.0.2](https://github.com/y20k/transistor/releases/tag/v4.0.2)), that fixes this problem. It should find its way to Google Play and F-Droid in the next couple of hours/days.
