### ISSUE TITLE
Color chooser for Play button and accent color

### ISSUE THREAD

**Issue by jamal2362** [y20k/transistor#282]
Actually it would be good if you could choose a color for the play button and the accent color in the settings.

Like this:
![G67jL](https://user-images.githubusercontent.com/15986930/87066589-1a527480-c213-11ea-94d0-b09d8314df44.png)

![Screenshot_20200709-183440](https://user-images.githubusercontent.com/15986930/87066483-ef682080-c212-11ea-8f32-8d50dc6cb17e.jpg)

![Screenshot_20200709-183417](https://user-images.githubusercontent.com/15986930/87066493-f2fba780-c212-11ea-88b9-1104f0b23716.jpg)

**Comment by y20k** [comment]
@jamal2362 

I have the urge to preface my answer with the following: I really and honestly like that you bring up a lot of fresh ideas to this project. So when I am saying no to some of them, PLEASE don't take that personally.

That said. There are two reasons why I am probably not going to implement a color chooser. The main reason would be:
1. I simply don't like the concept of letting users colorize the app. Mainly because I want to **stay in control** of Transistor's appearance. But also because I think accent color and app icon color should somewhat relate to each other. Plus: I think theming should be a system-wide thing.
2. I do want to keep the reliance on external libraries to an absolute minimum. So if I would want to add a theming option, I would not want to use a [third party library](https://github.com/the-blue-alliance/spectrum). As a consequence I would have to implement the color chooser by myself - which will, given the small time budget I have for this project, never happen.

Cheers
