### ISSUE TITLE
App not compatible with Android 7.0

### ISSUE THREAD

**Issue by crone123** [y20k/transistor#299]
**Describe the bug**
The min SDK version is too high, the app is not compatible with the major part of all android devices.
Maybe you can reduce the min SDK to the very requirement of the app, to allow more user to use your app.
I don't think the app uses features that justify a 7.1+ SDK..

**To Reproduce**
Go to FDroid with an 7.0- Android device, and you can't install the app.

**Expected behavior**
An app compatible with less recent devices, maybe 4.0+, or 4.1+ devices?

**Device:**
 - Device: Samsung Galaxy Tab S2
 - OS: Android 7.0 (Samsung Official ROM, not rooted)
 - Version: 7.0

**Comment by y20k** [comment]
I am a bit in a hurry right now. Please forgive my brevity. This issue is basically a duplicate.

See: [Previous discussions and feature requests #readmefirst](https://github.com/y20k/transistor/issues/48)
and there: [Support Android Jelly Bean (4.1 / 4.2 / 4.3)](https://github.com/y20k/transistor/issues/38)
and: [Kotlin-Rewrite](https://github.com/y20k/transistor/issues/251)

The short version. Transistor is a single person project. I have a job and family. I need to choose how to spend my time. I am not able to support older devices. Sorry.
