### ISSUE TITLE
Simultaneous playback of several radiostations

### ISSUE THREAD

**Issue by btimofeev** [y20k/transistor#31]
Bug: sometimes two radio stations start playing simultaneously.

How to reproduce bug: long tap to station, then quickly long tap on another station, then on another station, etc.

**Comment by y20k** [comment]
I experienced the same behavior. I am on it. Thanks for filing this bug.

**Comment by y20k** [comment]
Bug is still there. I am still on it. Hoping to fix it within this week.

**Comment by y20k** [comment]
This is a tricky one. I guess I at least know the source of this problem: The MediaPlayer object within the [PlayerService](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/PlayerService.java) class is prepared on another thread. 
`mMediaPlayer.prepareAsync();`
The method `onPrepared` is waiting for the results. Tapping on a second/third station causes the MediaPlayer object to be prepared with another stream URL - again on a separate thread. This way several background threads are preparing several objects (!) at the same time.
Problem is that I cannot cancel an already started Async thread. I need to further dive into that.

**Comment by y20k** [comment]
I am pretty sure, that the last [commit](https://github.com/y20k/transistor/commit/0add99e8ed24320e2fbce949ae38370537a0a72a) solved the main issue. Long-pressing too many stations in quick succession does not play multiple streams anymore. It still is not advised to do so since the implementation is still kind of buggy. I guess I will not advertise this feature for now.

**Comment by y20k** [comment]
I am closing this for now.
