### ISSUE TITLE
Edit stream URL

### ISSUE THREAD

**Issue by Neppo-muk** [y20k/transistor#319]
**Describe the solution you'd like**
Add a possibility to edit the stream url. This helps to change it, if the radio station did change it or to select a different stream quality (bitrate). Could go the same way as change the station name.
And let us select pictures, which were already known (from the images subfolder within the app)

**Describe alternatives you've considered**
Changed the URL in the json file (collection subfolder), but there is a high risk to mess up the file.

**Comment by y20k** [comment]
@Neppo-muk 

I understand the intention here. I wanted this for myself, too. 

But I think it is too much of a power user feature. Casual users do not understand the difference between: (a) station website (b) playlist link (c) streaming link. I would have to build a UI that covers all those cases. Given the small time budget I have for Transistor, I will probably not implement this.

The feature aimed at casual users for the scenario that a streaming link is out of date, is: Settings > Station update. I know it does not cover the scenario where a user wants to replace a working streaming link with a better one.

I will add the tag `help wanted` and add the issue to [Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48) and [CONTRIBUTE.md > Suggested-issues-to-tackle](https://github.com/y20k/transistor/blob/master/CONTRIBUTE.md#suggested-issues-to-tackle)

I currently see two possible implementations:

**"Edit streaming" link option (preferred)**
This should (1) resolve playlist links and mime type check the contents (2) have a good error message, when a user tries to enter a website link

**"Add to existing station" option**
This could be an option in the search/add dialog. Since it would probably add an additional step to adding new stations, it is not the preferred solution.

As always. If anyone wants to tackle this issue. Please contact me first.

**Comment by y20k** [comment]
I actually started working on this :-) see #389
