### ISSUE TITLE
Add option to sort by category or genre

### ISSUE THREAD

**Issue by shom13** [y20k/transistor#400]
**Its a little problematic to scroll if there is a long list of saved radio stations.**
 

**Add option to sort by category or playlist**.
 
Hi, firstly i love the app, but its missing a sort option. If only you could add a 'add to category' option, it would be really helpful. It doesnt have be done automatically, but can be manually sorted by the user.
Thanks.

**Comment by y20k** [comment]
Hi @shom13 

the use case I see Transitor being good at is in my opinion: A user has a set of 5-25 radio stations he/she likes. That is at least how I use the app myself :smiley:. Anyway. From time to time I hear from users that have way more stations stored in Transistor. In those cases I understand that just having a list (plus the ability to "favorite" stations) is not enough. I wonder if those users (and probably you, too) are better served by another radio apps like [RadioDroid](https://github.com/segler-alex/RadioDroid). I mean radio apps that meant to be used as radio station browsers.

In any case. I am super hesitant to add new UI elements to the app, since I deliberately want Transistor to be a simple app. So... I am sorry to disappoint you. But I have no plans at the moment to add any sorting features to the app.
