### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by tehabe** [y20k/transistor#47]
In some comments it was mentioned that some people miss this feature. I think it is not a top priority but with Chromecast Audio it would make sense to have a basic support for it in the app.

**Comment by y20k** [comment]
Hi there,

first of all. Thank you for contributing! I really enjoy all the feedback this little App got in the last couple of weeks. I think being able to stream audio from the phone to your stereo is very useful feature! I don't own a Chromecast though.

Two thoughts on this.

1. From the developer documentation it looks like you would need to have Google Services installed. Does Chromecast require you to be logged into a Google account to be able to cast audio? If so that could be a reason not to support it, since I don't like lock-in strategies a la Google/Facebook/Apple. If no Login required I would need to check if requiring Google Services would kick Transistor out of F-Droid. And lastly I would need to evaluate how complicated Chromecast integration is in practice ;-). All that said. I think casting the audio to your stereo is a very useful feature.

2. Over the fence on the iOS side they have a similar feature. AirPlay seems to work without the developer having to support it. The user just needs to select an AirPlay client from the Control Center and then the audio playing right now is being rooted to this client. What about Chromecast? In the Notification drop-down menu on my Nexus 5 (Android 6) there is a "Cast" icon. What happens when you press it? If audio can be send to a Chromecast via the system I think the App does not need to implement it. It does not have a Bluetooth button either.

Since I personally own a little DLNA box running Volumino I would like to I implement DLNA support. But I am a bit afraid that could proof to be quite complicated.

**Comment by tehabe** [comment]
Yeah, the _Cast_ button works, it just broadcasts the current screen and audio to the Chromecast. I only have one with video, so I don't know how the audio version works.

So it isn't pretty.

**Comment by y20k** [comment]
@tehabe There was another hidden question in this rather long comment of mine:

* Can you operate a Chromecast without being logged in to Google? Do you need a Google account for setup?

I did try to google that question but I did not get a satisfying answer.

Best wishes, have a nice weekend.

**Comment by tehabe** [comment]
Nyes leaning to no. You can put a Chromecast into a guest mode but isn't really the same I think. I tried it today with an Android device w/o Google account.

**Comment by y20k** [comment]
Okay. THX. 

F-Droid, which hosts Transistor too, has a list of [Antifeatures](https://f-droid.org/wiki/page/Antifeatures) which as I understand includes Google Play Services.

That does not mean Chromecast is off the table. I could imagine maintaining a non-free fork of Transistor. I will look into it. It may take a while though. I think I will get myself a Chromecast Audio for testing.

PS. Note to future self: Found a nice DLNA library worth considering for implementation in Transistor: [Cling](http://4thline.org/projects/cling/core/manual/cling-core-manual.html#chapter.Android)

**Comment by y20k** [comment]
I will close this issue for now and move it to the "Previous discussions and feature requests (#48)". I think I will reopen it when I buy Chromecast.
