### ISSUE TITLE
Station shortcut on desktop

### ISSUE THREAD

**Issue by azixMcAze** [y20k/transistor#53]
Hi, thank you for your nice app.
It would be great to be able to put shortcuts for stations on the homescreen. When you tap the shortcut, the station would start playing directly.
I'm not talking about a widget but simply a shortcut.

**Comment by y20k** [comment]
Hi there,

that was a feature I too was thinking about. I do not have any idea how to implement it though :-). 

There are some practical problems here because I do not know how to relate a shortcut to a station, since the stations are not stored in a database. Every solution I can come up with is somewhat hack-y.
Right now I am still working on the apps basic functionalities - but I will come back to this issue.

Best wishes

**Comment by azixMcAze** [comment]
Thanks for your quick reply.
I know that both ServeStream and Radio FM allow that, if you want some inspiration.

Cheers

**Comment by glitchphan** [comment]
Why not a widget with play/stop/next station/previous station? Kind of like XiiaLive and VLC.

**Comment by y20k** [comment]
Hi there. 

Thank you for sharing this idea! 

Adding additional functionality to secondary UI parts like notifications and widgets causes problems, if the main UI does not support those functionalities (see #46). I would need to add pause/next/previous to the main UI. But I do not want to do that. 

As a developer of a project that tries to stay VERY minimal in its feature set, I unfortunately have to say no way too often. 

So: Sorry, but no :-)

Best wishes

**Comment by glitchphan** [comment]
How about just play and kill buttons on it instead?

**Comment by y20k** [comment]
I have not started to write a single line of code for the shortcut/widget feature. I'll consider your suggestion when doing so. But since I am right now working on other enhancements, do not expect rapid progress on this issue for now :-). I am working on this in my (rare) free time. So do not be disappointed.
Best wishes

**Comment by glitchphan** [comment]
I don't ask for more than that :). Thanks.

**Comment by y20k** [comment]
:+1:

**Comment by azixMcAze** [comment]
Hi, I started working on the shortcut creation. There are still a few problems but I have something that is starting to work

**Comment by y20k** [comment]
Hi there that is great news. I am looking forward to your suggestion/solution. To avoid misunderstandings or disappointment it is probably good to discuss the general way you are planning to implement this feature. I had a case where I had to reject a pull request because of a general misunderstanding. I am bit too tired right now.I  will explain the way I thought I should work tomorrow. Best wishes. Good night Internet.

**Comment by y20k** [comment]
Hi there,
in the newly opened Transistor Wiki I wrote a short specification on how I think this feature should work . (See: [Station Shortcuts on the Homescreen](https://github.com/y20k/transistor/wiki/Station-Shortcuts-on-the-Homescreen)). Please consider this only a s starting point for a discussion. The specification is not set in stone! But I think it is important for us the be on same page. I had to reject a pull request ([#46](https://github.com/y20k/transistor/pull/46)) once because of a misunderstanding. That was very unfortunate and I want to do better this time :-). 
Best wishes, happy Sunday

**Comment by azixMcAze** [comment]
Hi!
No worries, I started the development of shortcuts mainly to see what is possible and to familiarize myself with android dev because it is a bit new for me.

Regarding you specifications, I also added an item to the context menu of the station in the main activity because it is the easiest. But it seems that it is not the "canonical way" to create shortcuts in android and it uses an allegedly undocumented permission and might no work everywhere (see http://stackoverflow.com/a/6337645 )

The user should also be able to go in "widgets" menu of his home screen and add a Transistor station shortcut from there. This would open a station picker and then place the selected station on the home screen.

Renaming the shortcuts is only possible for the user from the home screen if the launcher supports it. Apex and Nova Launcher both support it but I don't thinks Google Experience Launcher supports it. If the user has renamed the shortcut don't think Transistor will be able to delete it.

Managing the shortcuts from Transistor after they have been created looks like a tricky business! But hey, when there is no solution, there is no problem!

About the identification of the station in the shortcut, I arrived to the same conclusion : the most reliable identifier is the stream URL, iven if it can change (the station broadcaster changed it).

---

Concerning my implementation, I put the same intent you use to launch the `PlayerActivity` in the shorcut with the action `org.y20k.transistor.action.PLAY`.
I had to move the creation of the `PlayerService` from `onCreateView()` to `onCreate()`

The station picker for the launcher's widget menu have a lot in common with the `MainActivity`. I think I have to create a base fragment class for both with all the station listing code.

My WIP : https://github.com/azixMcAze/transistor

Have a nice day

**Comment by y20k** [comment]
> I think I have to create a base fragment class for both with all the station listing code.
That sounds reasonable ;-).
Happy coding.

**Comment by y20k** [comment]
FYI. I am rewriting parts of MainActivityFragment.java right now. I am switching from ListView to Recycler.View Should be ready within the next couple of days. That maybe of interest for your implementation.

**Comment by meonwax** [comment]
Happy merging :D

**Comment by azixMcAze** [comment]
Ahah :)
I am still trying to get the shortcuts to work correctly, I have not started to work on the station picker so this should not be too difficult to merge

**Comment by y20k** [comment]
Okay. I am glad that we are not in trouble here.

**Comment by azixMcAze** [comment]
Hi, I have something that you can try.
The shortcuts are still created from the contexts menus, not from the home screen.
I use only the stream URI in the shortcut and get the ID when receiving the shortcut.
I use either the station image or the app icon as the shortcut icon. I do not add a rounded shape or an antenna to the icon.

I had a lot of problem when I started directly PlayerActivity from the shortcut. I moved all the code to MainActivityFragment and everything is working a lot better now.
I hope I did not broke anything while merging your changes from MainActivity

I cannot create a pull request yet. I am new to git and I have some trouble excluding a commit from the PR.
But in the meantime you can checkout the code there : https://github.com/azixMcAze/transistor.git

**Comment by y20k** [comment]
Hey that is great news! I will have a look into your merge suggestions and will try to implement them.

**Comment by y20k** [comment]
Hi there. I did merge your code manually. I am not sure if I got everything. Can you please try to check? You maybe want to download the whole project and try to build it.

**Comment by y20k** [comment]
On my phone the shortcut creation does not work. I probably did miss something while merging. 

I already have a few questions:

1. I was wandering if the feature works on alternative Home screens - for example on Nova Launcher or on Samsung's Home screen.

2. While looking through the code I found that you request a few additional permissions. Are they all necessary?
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
`<uses-permission android:name="android.permission.READ_PHONE_STATE" />`
`<uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT" />`

3. PlayerActivity has a new intent-filter `<action android:name="org.y20k.transistor.action.PLAY" />`. Is that necessary?

4. There is no method that deletes the shortcut when a station within Transistor is deleted yet, right? No pressure here.... You do not need to implement that (but you can, if you want). Since you know more about shortcuts than me, maybe you can tell me how that feature could be implemented.

PS. Thanks for the good work so far!

**Comment by y20k** [comment]
I forgot to copy over the broadcast receiver. It now works on my device (Nexus 5 & Nova Launcher). :+1:

**Comment by y20k** [comment]
I did update the [Wiki page](https://github.com/y20k/transistor/wiki/Station-Shortcuts-on-the-Homescreen) a little bit. There is a design suggestion for the station shortcut. 

![example](https://cloud.githubusercontent.com/assets/9103935/13752316/7362aac2-ea0e-11e5-8fbc-b49c270337a7.png)

I will provide the necessary background drawables  soon. I will also update the ImageHelper class to be able to provide composed station shortcut images.

And I think it would be good to introduce a new ShortcutHelper class to have a better separation of code. I will provide that soon, too.

**Comment by azixMcAze** [comment]
Hi !

These new permission are completely unnecessary. They were added by Android studio with a bunch of other stuff when I Imported the project. That's the commit I wanted to remove from the PR.
I was going to try to discard the changes from this commit in a new branch before trying again to create a PR.

I did not add an option to remove the shortcut from the homescreen because I did not find a way to check if the shortcut is actually present on the homescreen. And if the station url is changed, the shortcut can't be found and cannot be deleted. Do you think there should always be an option in the context menu to remove the shortcut ?

The shortcuts are correctly added on Nova and Apex but I don't know if it is working on other OEM launchers (potentially not derived from AOSP)

I found that the PLAY action was necessary when the shortcut linked directly to PlayerActivity and I forgot to move the intent filter to `MainActivity`. Since it is working without it you can remove it.

It will be necessary to have a ShortcutHelper when it will be possible to add shortcuts from the picker activity

**Comment by y20k** [comment]
Hi there,

I did add/change the following stuff (see [commit](https://github.com/y20k/transistor/commit/b5084a4c5588d803a6513956bc17d8f3a622b10b)):

- removed the permissions that were not necessary
- rewrote the `ImageHelper` so that it can create custom shortcut icons
- changed your `createShortcut` to make use of ImageHelper
- created a new `ShortcutHelper` class

Next I will take out `createShortcut` and `handleShortcutIntent` from `MainActivityFragment` in favor of `ShortcutHelper`. Please do not write any new code until then.

Apropos new code: I really would like the delete-feature within Transistor to delete the Home screen shortcut alongside the station within Transistor. 

> I did not find a way to check if the shortcut is actually present on the homescreen

**So if anyone here has an idea... would be great.**

As far as the time frame for publishing the new feature. I plan to ship it alongside the new Sleep Timer and the Tablet Version. Both still need a lot of polish. So please be patient. In the meantime I did add your GitHub handle to [AUTHORS.md](https://github.com/y20k/transistor/blob/master/AUTHORS.md).

**Comment by y20k** [comment]
I did tweak the design for the shortcuts a bit yesterday.

![2016-03-17 16 44 35](https://cloud.githubusercontent.com/assets/9103935/13872563/da01beaa-eceb-11e5-8999-b78c2564001d.png)

**Comment by y20k** [comment]
Hi @azixMcAze,

I tried to implement the remove feature (see [ShortcutHelper](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/helpers/ShortcutHelper.java#L80)). 

As far as I understand the intent for removing must be exactly the same as the one for adding - with the exception that the intent for removing has the action `com.android.launcher.action.UNINSTALL_SHORTCUT` instead of `com.android.launcher.action.INSTALL_SHORTCUT`.

Is that your understanding, too? Can you please see if / where there is an error in my implementation?

Best wishes
Christian

**Comment by azixMcAze** [comment]
Hi @y20k !
This is also my understanding. I checked your code, and it seems correct. Is it working ? I am not sure if the icon is necessary when deleting the shortcut. Does it works without adding it to the intent ? Or maybe more importantly, does the removal still works if the user changes the station icon inside transistor.


I also started to implement the shortcut picker from the home screen. For the moment i duplicated the classes `MainActivity`, `MainActivityFragment` and `CollectionAdapter`. Maybe creating a base class is not the best way of factoring the code and creating a new helper might be a better solution. I have to try a few solution to see which one is the most elegant.

I also think that putting `CollectionAdapter.handleLongClick` and `CollectionAdapter.handleSingleClick` methods inside `MainActivityFragment` and calling them from a listener passed to `CollectionAdapter` from `MainActivityFragment` (instead of the listener created in `CollectionAdapter.onBindViewHolder`) may allow to use the same `CollectionAdapter` class without adding a lot of if/elses inside.
You moved this code from `MainActivityFragment` to `CollectionAdapter` recently if I remeber correctly ?

Cheers,
Mathieu

**Comment by y20k** [comment]
Hi @azixMcAze ,

> I checked your code, and it seems correct. Is it working ?

No. It is not working. If found a discouraging comment from an ASOP project member: ["We've completely removed support for the UNINSTALL_SHORTCUT intent in AOSP Launcher3 and Google Now Launcher. Currently there is no alternative or replacement for this API."](https://code.google.com/p/android/issues/detail?id=188908)

I guess sooner or later they will provide a new way to uninstall shortcuts. If you (or someone else reading this) finds out about a new or alternative way to archive this, please comment.

Best regards
Christian

**Comment by y20k** [comment]
Hi @azixMcAze ,

> You moved this code from MainActivityFragment to CollectionAdapter recently if I remember correctly ?

I did switch from ListView to RecyclerView. It seemed to be the way to go if one wants to implement animations and touch gestures to list-style layouts (see [Android Developers Blog](http://android-developers.blogspot.de/2015/10/android-support-library-231.html)). One drawback is: There is no OnItemClickListener in RecyclerView. Touch events are now supposed to be handled by each list item individually.

> ... putting CollectionAdapter.handleLongClick and CollectionAdapter.handleSingleClick methods inside MainActivityFragment and calling them from a listener

If you come to the conclusion that this is the most elegant way, we should go for it. On the other hand I welcome any attempt to slim down MainActivityFragment right now. That's why I did not mind putting those methods into the CollectionAdapter.

Best regards
Christian

**Comment by y20k** [comment]
Oh thanks. Fixed it.

**Comment by y20k** [comment]
mission more or less accomplished in [v2.0.0](https://github.com/y20k/transistor/releases/tag/v2.0.0) - time to close this one
