### ISSUE TITLE
Better notification

### ISSUE THREAD

**Issue by pelya** [y20k/transistor#58]
The notification could see a few improvements. I'll fork your code and try to fix some of these myself next week.

1. Notification has 'content hidden' while in the lockscreen. This is fixed with VISIBILITY_PUBLIC flag.

2. 'Swipe to stop' will kill your app on some devices at random (some Sony and HTC phones aggressively kill all background tasks), and also when user taps 'Clear all' button. What you need is 'Tap to stop', or even better full controls with prev/next/close buttons. And you need to create this notification by creating a Service and calling startForeground() on it. I've got a similar patch for KDE Connect lying around, I'll adapt it for Transistor (and those lazy bums won't merge my patch after 4 months, and also KDEConnect on PC messes up all windows at random, so I'm back to using MPD, why all reliable music stuff on Debian must come in a console-only form?).

3. Artist and song names from a stream ID3 tags or Shoutcast metadata, displayed in a nice marquee. I can submit a patch for marquee :)

**Comment by y20k** [comment]
Hey pelya, 

Thank you for you comments. I'll try to answer:

1. **VISIBILITY_PUBLIC**: I did not know about this flag. I implemented it. Thanks.

2. a. **when user taps 'Clear all' button**: I am aware of that behaviour and I am considering to add a stop icon and ditch the swipe to stop gesture (although I really like it) 
b. **even better full controls with prev/next/close**: I do not like prev/next buttons. Although I know that some/many users would like to have them (see  #46)
c. **create this notification by creating a Service**: Now that is a very interesting suggestion! I was not aware that notifications get killed by the system. If you know any interesting discussions or blogs etc. on that issue of the top of your head, **please drop me a link here**. I might also come back on you offer. I need to persuade myself first that this is a good solution

3. **ID3 tags or Shoutcast metadata**: I would love to have metadata. I did try to get metadata from the streams but it did not work (see issue #33). If you have an idea how to do that (without adding non core-libraries), feel free to reopen the issue.

**Comment by Cormak** [comment]
I was about to make this issue. @pelya summed it up even better than I was planning to. All 3 improvements are welcome.

**Comment by y20k** [comment]
Now that we have station metadata - it is time to change the notification style a bit.

![notification](https://cloud.githubusercontent.com/assets/9103935/14611741/10f44836-0594-11e6-99af-92d54df25cc3.png)

**Comment by pelya** [comment]
So you finally decided to include buttons into the notification? What about
Prev/Next buttons, are you still against them?
I would love to use some kind of a swipe gesture to switch between stations
from the notification, but I don't think that's possible.

I submitted another merge request, with custom notification layout and
scrolling song text.
Please do not merge it yet, I just want to know if you like the general
idea.
Prev/Next buttons do not work yet, and I'll agree if you wish to remove
them.

**Comment by y20k** [comment]
Hi there,

**A. Notification: handle long metadata string using marquee**
I did install [your suggestion](https://github.com/pelya/transistor/tree/CustomNotification) on my phone and I did a test run. I am a bit reluctant to dismiss it, because you already invested some time into it.

But I think a custom notification style is not really necessary. The standard way to handle longer text in notifications seems to be: Let it overflow into the expanded notification. For now I think I would like to stick with it. In the current implementation overflow-to-bigstyle works fine.

One thing I want to change with the current notification is: The "&#x25a0;" icon (without text) should also be visible in the small notification. That should somehow work with `setShowActionsInCompactView(0);`. I guess I need to implement MediaSession (#70) first.

**B. Notification: Prev/Next buttons?**
I do not see the benefit right now. Maybe I need to get myself Android Auto or Wear to appreciate the idea that one wants to navigate Transistors radio stations without using the list view. For Transistor to work on those platforms also MediaSession (#70) is a prerequisite, I believe.

Best regards.

**Comment by pelya** [comment]
Okay. AndroidCompat library provides standard notification style with media
controls, but you can override it with your own style I think.

**Comment by M2ck** [comment]
@y20k & @pelya Just an idea about Prev/Next feature, it will be possible to get these actions using +/- volume buttons?

**Comment by pelya** [comment]
Changing button picture will simply do it more confusing.

**Comment by M2ck** [comment]
>Changing button picture will simply do it more confusing.
Maybe that I misspoke sorry.
No need to change or add anything to the notification done above with only a Stop button, but using +/- hardware volume buttons for get Prev/Next actions.
Just an idea anyway :)

**Comment by pelya** [comment]
Reassigning hardware volume buttons to something else than changing volume
is straight evil, especially in a music player.

**Comment by y20k** [comment]
Here is what the new notification looks like on Android N. Interesting how much Google changed the general styling of notifications compared to Android 6 (see above). Conservative, as I probably am, I like the old style better :-)

![2016-04-21-18 54 43](https://cloud.githubusercontent.com/assets/9103935/14743606/98b909e4-08a2-11e6-9827-6bf7e5a926b6.png)

**Comment by y20k** [comment]
The new enhanced notification is now part of [v2.0.1](https://github.com/y20k/transistor/releases/tag/v2.0.1). Thanks again for the very valuable help.
