### ISSUE TITLE
Dowload issue

### ISSUE THREAD

**Issue by bastorran** [y20k/transistor#6]
Hello,

I got a similiar error like issue #5 with this address:
http://internetradio.salue.de:8000/classicrock.mp3 
(from here: http://www.classicrock-radio.de/musik/webradio.phtml, it's the same with the aac stream)

Thank you for your app!

**Comment by y20k** [comment]
Hi there,

the error is similar but in a way different too. I think your problem is not that easy to solve (sorry).

Transistor only works with streams embedded within m3u and pls files. The URL you provide is the raw stream URL that is usually encapsulated within a m3u file. A quick and dirty fix would be to write your own m3u file in a raw text editor and place it into /Android/data/org.y20k.transistor/Collection  (see/download below).

Problem is that Transistor only does a plausability check on the given files. It does not actually check if there is streaming media. One of the checks is the file extension of a given URL. Only m3u and pls are allowed.

Making Transistor open to any given URL would open it to a lot of bug reports from people who try all sorts of URLs - eg just the URL of the homepage of a station. 

So until I implement a working check routine (which maybe starts a stream in background while adding it) I do not want to loosen the rules of the plausability check.

Best wishes


Classic Rock.m3u
- Download:
https://drive.google.com/file/d/0B2Qc4v5vxiQbRGlFcGludDQ4R1k/view?pref=2&pli=1

- File Content:
#EXTM3U

#EXTINF:-1,Classic Rock
http://internetradio.salue.de:8000/classicrock.mp3

**Comment by y20k** [comment]
I will close this issue, but I am still working on it. On #22 someone had a good idea how to solve it. It may take some time though.
