### ISSUE TITLE
mms or rtsp support?

### ISSUE THREAD

**Issue by sunng87** [y20k/transistor#7]
Most of my stations are `mms://` based. Currently we cannot input mms url to transistor. I hope you can add support to mms. Thanks!

**Comment by y20k** [comment]
In Transistor I use the official MediaPlayer library. Judging from the Android developer documentation[1] it sounds like RSTP is supported. To check if MediaPlayer can handle your stations, please post example links for mms:// and rstp:// each, if possible.
Maybe your problem is related to #6. Transistor currently only supports streams that are encapsulated in m3u or pls. Check out my answer to #6 for more details. 

[1] http://developer.android.com/guide/appendix/media-formats.html

**Comment by sunng87** [comment]
My station url is: mms://alive.rbc.cn/fm1006

I will try your fix in #6 later to see if it works for me. Thank you very much for your response and this app!

**Comment by sunng87** [comment]
Hi @y20k , the workaround doesn't work for me. After looking into the code, I found the m3u parse may only support stream url starts with `http`.

**Comment by y20k** [comment]
Hi there, 

oh. Thanks for the hint ;-). I forgot how that part of the parser was supposed to work. I did broaden the condition to allow http- as well mms-URLs. The next problem here is when I convert the mms://-String into a into a JAVA URL. I get an error - because URLs must be http. 

So if I want to test, if mms-links work, I need to rewrite quite a lot of code. Station URLs must be stored internally as JAVA URI instead of JAVA URL. That is in general not a bad idea. I will try that in the next couple of month. Be patient. I am working on this project in my free time. I leave this issue open so that you get informed about my progress.

Best wishes.

**Comment by y20k** [comment]
Hi @sunng87, 

short answer: It seems that mms:// Streams are not supported by the MediaPlayer library. But RSTP is likely to work.

Here is what I tried: I changed the way stream URLs are stored within Transistor to be URI as planned. I also allowed "mms" strings to be parsed as stream URLs. Then I made an M3U ( [Alive RBC.m3u](https://drive.google.com/file/d/0B2Qc4v5vxiQbNERWRXFoNzYyQVk/view) ) from your station and placed it into Transistor's Collection folder. When I started Playback I got MEDIA_ERROR_UNKNOWN from MediaPlayer. Dead end. :-(

There is maybe hope for RTSP. The [Android API Guides](https://developer.android.com/guide/appendix/media-formats.html) explicitly mention RTSP as a compatible format. Do you have any RTSP streams that you would like me to  test?

**Comment by sunng87** [comment]
@y20k Perhaps you can use rtsp://alive.rbc.cn/fm1006 for testing. I tested via mpv, it works:

```
 $ mpv rtsp://alive.rbc.cnfm1006                                                                
Playing: rtsp://alive.rbc.cn/fm1006
 (+) Audio --aid=1 (wmav2)
File tags:
 Artist: www.rbc.cn
 Title: 北京新闻广播
AO: [pulse] 32000Hz stereo 2ch float
A: 00:00:01
```

**Comment by y20k** [comment]
Okay. Thank you very much! I tried RTSP by adding a parser rule for "rtsp". Again with negative results :-( I am sorry. 

I am not an audio expert. Both streams (mms and rtsp) seem to provide audio that was compressed using WMA2. So while the RTSP protocol seems to be supported by the MediaPlayer library, the WMA-codec maybe isn't. At least that is what I am thinking right now. 

If that is really the case only the change to a new non-native playback library would solve this issue.

Screenshot from VLC playing rtsp://alive.rbc.cn/fm1006
![vlc_rtsp](https://cloud.githubusercontent.com/assets/9103935/12392098/a2d5f050-bdec-11e5-8186-32e58a2588ec.png)

**Comment by sunng87** [comment]
According to [this answer](http://stackoverflow.com/questions/7026292/android-medioplay-how-to-play-http-or-rtsp-stream) wma2 is not supported by Android MediaPlayer.

I'm using TuneIn to play it at the moment but I found TuneIn is too heavy so I was looking for some alternatives and found transistor. 

Thanks for your time on this issue.

**Comment by y20k** [comment]
You are welcome. Thank you in return for the excellent bug report! I am sorry that I cannot help you for now. I was using TuneIn, too. TuneIn was actually the reason why I started Transistor ;-). 

Best wishes.
