### ISSUE TITLE
Resume playing on quick headphone reconnect

### ISSUE THREAD

**Issue by infozsoda** [y20k/transistor#73]
It would be awesome if disconnecting the headphones triggered a short timer (60 seconds?), and if the user reconnects the headphones before the timer fires, the audio resumes playing.

This would help with snagged cables, as well as "loose" headphone ports.

**Comment by y20k** [comment]
Hey @infozsoda, 

sorry for answering a bit late. I was AFK for a few days. 

Anyway. Thank you for your suggestion. I get why this feature can be handy in some/many cases. But there is a "but". 

Since the suggested behavior is a non-standard behavior it would require me to introduce a settings page. But Transistor is conceptually a very simple non-settings app. see also: ["Resume play on audio jack plug-in"](https://github.com/y20k/transistor/issues/59). I do not want to change that at this point.

So: No settings -> No "Resume playing on quick headphone reconnect"

Best regards
Christian
