### ISSUE TITLE
DF streams are not working

### ISSUE THREAD

**Issue by mgraupner** [y20k/transistor#78]
Today I tried to stream DeutschlandFunk over Transistor, both the MP3 and OGG Streams are not working for me, the MP3 one shows an error after downloading, the ogg one can be added to Transistor and also starts playing but I won't hear any sound. A test with the FM4 Stream worked as expected.

Stream URLs:
http://www.deutschlandradio.de/streaming/dlf_hq_ogg.m3u
http://www.deutschlandradio.de/streaming/dlf.m3u

Thank you for your otherwise great little tool, it really fills a niche for me as an open source Android webradio player.

**Comment by y20k** [comment]
Hey mgraupner,

thank you for your bug report. Both streams work on my phone. Adding works, playback, too. This is a problem for me, because I do not know how to debug this. 

My guesses would be:
- OGG-playback maybe not supported by your device?
- The mp3 version cannot be added because there are old/conflicting files in /Android/data/org.y20k.transistor/Collection (where Transistor stores its stations)?

If you have a file manager for your phone... can you have a look into the above mentioned Collection folder?

You can also try to add one the raw streaming URLs below (copy/paste into the add dialog). I got those URLs from the m3u links you mentioned.

MP3 1
http://stream.dradio.de/7/249/142684/v1/gnl.akacast.akamaistream.net/dradio_mp3_dlf_m

MP3 2
http://dradio_mp3_dlf_m.akacast.akamaistream.net/7/249/142684/v1/gnl.akacast.akamaistream.net/dradio_mp3_dlf_m

OGG
http://dradio-ogg-dlf-l.akacast.akamaistream.net/7/629/135496/v1/gnl.akacast.akamaistream.net/dradio_ogg_dlf_l

Best regards

**Comment by mgraupner** [comment]
Hm, that's what I expected, device specific bugs :)

The OGG stream works in VLC for me and a OGG test file played without any problems in Firefox, but I don't know if these use the same libraries for OGG playback as Transistor.

Except of FM4.m3u there is no other file in the mentioned directory.

Perhaps if time permits you could add a debugging option which writes a log file which can be uploaded here so you can have a more detailed log.

Thanks for the direct links, the MP3 one works as expected.

**Comment by y20k** [comment]
:+1:
