### ISSUE TITLE
Notification UI issue

### ISSUE THREAD

**Issue by M2ck** [y20k/transistor#87]
Hi, just updated to the version 2.0.2 and I get a weird UI on notification.
OnePlus X - Android LP 5.1.1

V2.0.1 with a right notification (icon size, color, button position and with text)
![screenshot_2016-05-31-21-10-57](https://cloud.githubusercontent.com/assets/6850125/15687551/a54bf076-2775-11e6-8add-b94edb270782.png)

V2.0.2 with a weird notification (icon size, color, button position and without text)
![screenshot_2016-05-31-21-20-24](https://cloud.githubusercontent.com/assets/6850125/15687577/cedc77e4-2775-11e6-9e7e-93d6c85c36bd.png)

**Comment by MFreeHost** [comment]
I have the same issue  Nexus 5 Android 6.0.1

**Comment by y20k** [comment]
Hi there,

thanks for reporting this issue. By "weird" you mean: the STOP button is missing a text, right? This is not a bug (it is not a feature either). It is basically a compromise I choose to make. 

For v2.0.2 I did implement the standard UI for notifications that media apps are supposed to use: [Notification.MediaStyle](https://developer.android.com/reference/android/app/Notification.MediaStyle.html). 

This pre-defined style has one advantage over the one I was using before. It shows an **action button in compact view**. The old style did not offer that option.
![screenshot_nexus_5_lockscreen_en](https://cloud.githubusercontent.com/assets/9103935/15670931/3a1e62ea-2728-11e6-8d98-cae532c95ac4.jpg)
Since the app does not have _swipe to stop_ anymore, I really like this feature as an alternative for a quick action.

This style on the other hand has the problem you mentioned: In expanded view it does not show text next to the action buttons even if there is plenty of room.

I would suggest you wait a few days and see, if it still bothers you. If so, please come back here and lets discuss what the options are.

**Comment by M2ck** [comment]
I've updated my first post with screenshots for before and after v2.0.2, should be more explicit!

**Comment by y20k** [comment]
The new notification is layout-wise a valid notification. In fact it is the recommended style for media apps. A lot of other apps use this style, too. 

For example: PocketCasts
![pocketcasts](https://cloud.githubusercontent.com/assets/9103935/15690409/a7ebe940-2783-11e6-85fb-cb1ba84bef1d.png)

Compare:
![transistor](https://cloud.githubusercontent.com/assets/9103935/15690639/c0bb70f2-2784-11e6-8ad0-b87f34f80401.png)

As for now: I did not set any color yet (see [NotificationHelper](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/helpers/NotificationHelper.java#L124)). So the standard color (grey) is used. 

As I wrote before: If you feel there are (1) aesthetic issues or (2) usability problems after a few days, please come back.

**Comment by y20k** [comment]
>  I did not set any color yet (see [NotificationHelper](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/helpers/NotificationHelper.java#L124))

I just ran a test: If I set the color and result will look different on Android 6 and N:

**Android 6**
![notification-6](https://cloud.githubusercontent.com/assets/9103935/15723943/0bb72f36-2845-11e6-985f-623cb913b3c3.png)

**Android N**
![notification-7](https://cloud.githubusercontent.com/assets/9103935/15723985/5209aea0-2845-11e6-87fb-a53f5ed4b852.png)

**Comment by M2ck** [comment]
Ok I understand what you want mean.

**Comment by y20k** [comment]
Okay. Thanks anyway for discussing this issue here. I will continue to have a look into how the notification looks on all platforms. If Android N will support a bit more customizing I will revisit this.
