### ISSUE TITLE
Transistor can't play this pls station on Cyanogenmod 13

### ISSUE THREAD

**Issue by pizzadude** [y20k/transistor#90]
Hi, I can play this pls station in VLC but not Transistor.

http://playerservices.streamtheworld.com/pls/CBC_R1_OTT_H.pls

Phone is Moto G 2014 running CM13 (Android 6.0.1)

Screenshot of error https://my.mixtape.moe/eiadpv.png

What could be the issue? I saw a closed issue that was similar but the person was running kitkat

**Comment by y20k** [comment]
Hi there,

Transistor's error dialog is not very helpful sometimes. The problem here is that the PLS you tried to add contained a stream with an unsupported MIME type (`audio/aacp`). [I did add the missing MIME type](https://github.com/y20k/transistor/blob/a4174e2a40dade4d7a784eebbd8e148bf07e1b48/app/src/main/java/org/y20k/transistor/core/Station.java#L53)(*) and ran a test. The station plays. 

The fix will be part of the next release. I am not sure how long that will take though. If you are eager to try it out ... here is an APK for the current version of Transistor including the fix: [transistor-app-testing-2.0.3a-mime-type-issue.apk](https://www.dropbox.com/s/tha0rbzxkm33dlt/transistor-app-testing-2.0.3a-mime-type-issue.apk?dl=0)

(*) @meonwax of @pelya : this is maybe of interest for you.

**Comment by pelya** [comment]
When I've tried to play AAC stream on my device, it failed. Apparently
Android MediaPlayer does not support streaming AAC over the net, it only
supports local files, and this may be different in different Android
versions.
http://stackoverflow.com/questions/15225076/android-aac-radio-streaming-doesnt-work-with-mediaplayer-android-4-2-2-sho
http://vaclavb.blogspot.com/2010/06/raw-aac-player-for-android.html
http://stackoverflow.com/questions/1650983/streaming-aac-audio-with-android

**Comment by pelya** [comment]
Please make sure that you are using system libraries for AAC decoding, and
do not include your own AAC decoder into the app, otherwise you'll be hit
with nasty licensing fees.

**Comment by y20k** [comment]
@pelya : Now that you mentioned it... We had a similar issue a few month ago: [AAC doesn't play](https://github.com/y20k/transistor/issues/19). If it turns out that AAC does not work on CM. We should not support it. 

@pizzadude : You are using CM, right? Can you test the APK I provided above and report your findings?

> do not include your own AAC decoder

@pelya : That won't happen.

**Comment by pelya** [comment]
AAC did not play even on my Samsung phone, and I'm sure it has the license
and all libraries. You can enable the MIME type, it won't hurt, and at
least some phones will play it.

**Comment by y20k** [comment]
Okay. Maybe we could show a warning/Toast when someone tries to add an AAC stream.

**Comment by pizzadude** [comment]
Hi, I tested your test build in CM13 and it lets me add the stream. At first, I thought the stream wasn't playing when I pressed play, but it turns out I had to wait a while and it started playing.

I have seen similiar wait times in another application from F-Droid called RadioDroid, they are probably using the same method of streaming, but I'm not sure.

**Comment by pelya** [comment]
I did not know about RadioDroid app, nice find!

**Comment by y20k** [comment]
> turns out I had to wait a while

Same here. This kind of stream seems to take a while.

**Comment by pelya** [comment]
That's Android's MediaPlayer buffering, I don't know if you can control
that. Proxy data through a FIFO,  so it thinks it's reading from disk,
maybe?

**Comment by y20k** [comment]
The waiting itself is fine for me. With a wait time this long I should consider showing a "Buffering" indicator.

**Comment by pelya** [comment]
Hmm, how will you determine when it starts playing? You cannot capture
audio streams. Just set a 3 second timeout?

**Comment by y20k** [comment]
The playback should start when [onPrepared](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/PlayerService.java#L247) is called.

**Comment by pizzadude** [comment]
Unrelated, but seeing as the current version name is "Starman" I think it would be funny if the next release name is "Stallman". ;)

**Comment by middling** [comment]
On a Nexus 5 with stock Android 6 the stream in the OP works for me (albeit with a long buffering period).  [This AAC+ stream](https://www.animenfo.com/radio/listen-32k.m3u) doesn't though.  An `ffmpeg -i` on the streams shows that the OP's is using HE-AACv2 whereas the AnimeNfo one is using HE-AAC.

On a tangential note, in addition to MP3 and Ogg Vorbis, Transistor also seems to work with [streams](http://dir.xiph.org/by_format/Opus) using the [Opus Codec](http://opus-codec.org/) (also with a long buffering period and no metadata).

**Comment by pelya** [comment]
Please don't summon Stallman - this will change Transistor license to GPL.
Name it 'Never Gonna Give You Up' or 'Dragostea din tei' or something.

**Comment by pelya** [comment]
Android MediaPlayer should also support FLAC, MIDI, WAV, and 3GP:
https://developer.android.com/guide/appendix/media-formats.html

**Comment by middling** [comment]
Looks like part of the problem with the AnimeNfo stream is that they're sending the .m3u file with a mimetype of application/octet-stream.

Copying the .m3u across to my own server and setting the mimetype to audio/x-mpegurl allowed Transistor to add the playlist but the stream still won't play, so there's some other issue with their stream (metadata shows up but no audio).

Allowing Transistor to add playlists sent with `application/octet-stream` will probably help in cases where the streams are fine but there's a misconfiguration on the webserver serving the playlist.

**Comment by pelya** [comment]
The bug with octet-stream instead of x-mpegurl is solved by
https://github.com/y20k/transistor/pull/84  however I don't have enough
free time this week to clean up my patch.

**Comment by y20k** [comment]
Take your time. M3U-Playlists with the wrong MIME type do obviously exist, but they are an edge case. This is not really a bug of Transistor. Great that you have a solution in the working though! :+1:

**Comment by y20k** [comment]
Coming back to the issue "playback of AAC". The stream that @pizzadude had an issue with does play on Android 4.2 (in an emulator). I just tested it. I think we should keep audio/aacp in the list of allowed MIME types

**Comment by y20k** [comment]
I did add `audio/aac` and `audio/aacp` and I also did introduce a subtle warning when a user tries add an AAC stream (see [commit](https://github.com/y20k/transistor/commit/baa33bb03f466cdb66597104439c118f195ffc84)).

Since users have problems playing back AAC (#19) under certain conditions AAC "support" wont make it into the official product page on Google Play. 

**MP3 and OGG remain the only two officially supported formats for now.**

Most/many user still should be able to play back AAC though. Here is an updated APK of the latest beta: [transistor-app-testing-2.0.4b-on-error-reconnect.apk](https://www.dropbox.com/s/e2037nozuyhk0u8/transistor-app-testing-2.0.4b-on-error-reconnect.apk?dl=0)

**Comment by pizzadude** [comment]
Thanks for fixing this. :)

**Comment by y20k** [comment]
🖖

**Comment by y20k** [comment]
Unofficial AAC support is implemented in [v2.0.4](https://github.com/y20k/transistor/releases/tag/v2.0.4). Time to close this issue.
