### ISSUE TITLE
Can't add streaming URL of Energy FM

### ISSUE THREAD

**Issue by Daniel157** [y20k/transistor#91]
Hello there! I have a problem with transistor. I could add several stations without problems, but it won't add Energy FM for me. The streaming URL is as follows:

http://adwzg2.tdf-cdn.com/7649/nrj_125741.mp3

The error is a follows: "Transistor tried hard but could not make sense of the given link."

On my desktop PC this URL works without problems. But I noticed that it always plays an advertisment before starting the actual stream. Probably this is a problem for transistor.

**Comment by y20k** [comment]
Hi there,

the stream you mentioned is an AAC (despite of the file extension). AACs are currently not supported. But that will probably change with the next release.

Your bug report is a duplicate. We are discussing this issue here: 
[Transistor can't play this pls station on Cyanogenmod 13](https://github.com/y20k/transistor/issues/90)

If you are eager to test... There is an APK for the current version of Transistor including a fix for AAC: [transistor-app-testing-2.0.3a-mime-type-issue.apk](https://www.dropbox.com/s/tha0rbzxkm33dlt/transistor-app-testing-2.0.3a-mime-type-issue.apk?dl=0)
