### ISSUE TITLE
[Feature request] Add proxy server support

### ISSUE THREAD

**Issue by Nabif** [y20k/transistor#92]
It would be nice to be able to use a proxy server for the audio streaming.

**Comment by y20k** [comment]
Hi there,

Thanks for suggesting that feature! I can see that proxying a connection on a per-app basis can a good idea. But I think this is not a thing that Transistor should be able to do. Transistor is an app without any settings. It is supposed to be very simple. There are other apps out there with a more power user oriented profile. Those are probably a better fit for that feature.

Anyway. Just because I am curious... What is the use case you had in mind when suggesting that feature? As far as I can see there is a system-wide Proxy option under "WiFi". Why not use that?

Best regards.

**Comment by kaffeekanne** [comment]
I love the simple UI of Transistor. Anyway i would love to see proxy settings too.

Usecase: Route Trough orbot for privacy reasons. Stream provider can still count users/clicks, but should not be able to track listeners.

Of course i can add a custom script to afwall to achive this, but that is a big barrier even for advanced users.

Global proxy settings are not useful as i obviously do not want to route everything through Tor, especially local requests inside my LAN.

Just my thoughts, love your APP, would appreciate proxy settings!

**Comment by y20k** [comment]
sorry. but I really do not want to add a settings screen to the app.
