### ISSUE TITLE
Support AAC audio format

### ISSUE THREAD

**Issue by Cormak** [y20k/transistor#97]
MP3 and OGG is not enough. There's many more AAC streams than there are OGG streams, and often, an AAC stream is the only option on some independent stations.

Will we be getting support for it?

**Comment by y20k** [comment]
Hi there. 

Thank you for reporting this issue. Transistor actually should support AAC to some degree. This is not an official feature, since the AAC support seems to be device-dependent. Transistor uses the [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) library for playback. You can find the supported formats [here](https://developer.android.com/guide/appendix/media-formats.html). 

That said - some variants of Android will not play back AAC streams. Our guess was, that vendors maybe need to license the AAC codec for MediaPlayer to be able to play back AAC streams. See discussions: #19 & #90.

To be able to determine, if your issue is a duplicate one (#19 & #90), please post the URL of a station, that does not work, and your device model and Android version. That would be very helpful.

Best regards

**Comment by y20k** [comment]
I am closing this issue for now, because I think it is a duplicate. Feel free to reopen it, if you do disagree - and/or if you have more information.
 
Best regards

**Comment by y20k** [comment]
By the way: AAC should work now. See #137.
